// Copyright 2019 Ludan Stoecklé
// SPDX-License-Identifier: CC-BY-4.0
= RosaeNLG Tutorial for English

:rosaenlg_lang: en_US

++++
<script>
const currentLang = 'en_US';
</script>
++++

include::partial$tuto_fragments.adoc[tags=intro;node_setup;initial_data;plumbing]

++++
<script>
const phoneString = `-
  let phones = [
    {
      name: 'OnePlus 5T',
      colors: ['Black', 'Red', 'White'],
      displaySize: 6,
      screenRatio: 80.43,
      battery: 3300
    },
    {
      name: 'OnePlus 5',
      colors: ['Gold', 'Gray'],
      displaySize: 5.5,
      screenRatio: 72.93,
      battery: 3300
    },
    {
      name: 'OnePlus 3T',
      colors: ['Black', 'Gold', 'Gray'],
      displaySize: 5.5,
      screenRatio: 73.15,
      battery: 3400
    }
  ];
`
</script>
++++


++++
<script>
spawnEditor(currentLang, 
`${phoneString}

- let phone = phones[0];
p #{phone.name}
`, 'OnePlus'
);
</script>
++++


== List elements with the `eachz` structure

Let's talk about the colors of the phone: we want to output _Available colors are aaa, bbb and ccc._

Create a mixin dedicated to listing colors (in your `tuto.pug` file):
....
mixin colors
  | the phone's available colors are
  eachz color in phone.colors with { separator:',', last_separator:'and', end:'.' }
    | #{color}
....

* `eachz` is a RosaeNLG structure. It's like a foreach loop, with additionnal NLG features.
* `{ separator:',', last_separator:'and', end:'.' }` tells `eachz` that:
** the standard separator is the comma
** `and` should be used between the two last colors
** we should end with a dot

Call the mixin:
....
p #{phone.name} . #[+colors]
....

Run it. Output should be: _OnePlus 5T. The phone's available colors are Black, Red and White._

See how RosaeNLG managed the spacing between words and the automatic capitalization. This is called "Surface Realization" in NLG.

TIP: Now we are doing Natural Language Generation 🚀

++++
<script>
spawnEditor(currentLang, 
`${phoneString}

- let phone = phones[0];

mixin colors
  | the phone's available colors are
  eachz color in phone.colors with { separator:',', last_separator:'and', end:'.' }
    | #{color}

p #{phone.name} . #[+colors]
`,
"OnePlus 5T. The phone's available colors are"
);
</script>
++++


== Looping on all the phones

include::partial$tuto_fragments.adoc[tags=looping]

You should get: +
_OnePlus 5T. The phone's available colors are Black, Red and White._ +
_OnePlus 5. The phone's available colors are Gold and Gray._ +
_OnePlus 3T. The phone's available colors are Black, Gold and Gray._


++++
<script>
const mainString = `
${phoneString}

BEFORE

- let phone;
each phoneElt in phones
  - phone = phoneElt;
  MAIN
`;

const mixinColorsString =
`mixin colors
  | the phone's available colors are
  eachz color in phone.colors with { separator:',', last_separator:'and', end:'.' }
    | #{color}
`;

spawnEditor(currentLang,
  mainString.replace('BEFORE', mixinColorsString)
    .replace('MAIN', 
    `p #{phone.name} . #[+colors]`
  ),
  "OnePlus 5. The phone's available colors are Gold"
);
</script>
++++

== Basic synonyms

Readers love when texts are not repetitive. Let's add some very basic synonyms: _tints_ and _tones_ are synonyms of _colors_.
Change your `colors` mixin:
....
mixin colors
  | the phone's available #[+syn('colors', 'tints', 'tones')]
  | are
  ...
....

Run it multiple times and you should have different outputs.


++++
<script>
const mixinColors2String =
`mixin colors
  | the phone's available #[+syn('colors', 'tints', 'tones')]
  | are
  eachz color in phone.colors with { separator:',', last_separator:'and', end:'.' }
    | #{color}
`;

spawnEditor(currentLang,
  mainString.replace('BEFORE', mixinColors2String)
    .replace('MAIN', 
    `p #{phone.name} . #[+colors]`
  ),
  "he phone's available"
);
</script>
++++

== More synonyms

The `syn` mixin is perfect for words or part of sentences. But let's say we want create some introduction texts, and that we want to have diversity.

Let's put all these different introductions in a dedicated mixin:
....
mixin intro
  synz
    syn
      | the #{phone.name} is really a fantastic phone.
    syn
      | i really love the new #{phone.name}.
    syn
      | #{phone.name} : a great phone !
....

The `synz > syn` structure simply lists synonymic alternatives. You can put whatever you want in each alternative (in each `syn`): conditions, more synonyms etc.

Let's call this new mixin:
....
mixin printPhone
  | #[+intro] .
  | #[+colors] .

- let phone;
each phoneElt in phones
  - phone = phoneElt;
  p #[+printPhone]
....

You should get: +
_I really love the new OnePlus 5T. The phone's available tints are Black, Red and White._ +
_I really love the new OnePlus 5. The phone's available tints are Gold and Gray._ +
_OnePlus 3T: a great phone! The phone's available tones are Black, Gold and Gray._

Intros are chosen randomly so you might have repetitions.

++++
<script>
const mixinIntroString = `
mixin intro
  synz
    syn
      | the #{phone.name} is really a fantastic phone.
    syn
      | i really love the new #{phone.name}.
    syn
      | #{phone.name} : a great phone !
`;

const mixinPhoneString = `
mixin printPhone
  | #[+intro] .
  | #[+colors] .
`;

const main2String = mainString.replace('MAIN', `p #[+printPhone]`);

spawnEditor(currentLang,
  main2String.replace('BEFORE', [mixinColors2String, mixinIntroString, mixinPhoneString].join('\n')),
  'OnePlus'
);
</script>
++++

== List parts of a sentence

Let's talk about the display: physical size and screen-to-body ratio. We want to output something like _it has a physical size of 6 inches and a screen-to-body ratio of 80.43 %_.
We could build a big static sentence, but structuring the code will give us more flexibility.

Let's cut our big sentence in chunks, one for each property:
....
mixin display
  itemz { separator:',', last_separator:'and' }
    item
      | a physical size of #[+value(phone.displaySize)] inches
    item
      | a screen-to-body ratio of #[+value(phone.screenRatio)] %
....

include::partial$tuto_fragments.adoc[tag=display_elts]

The result is not that bad, but the beginning of the text is missing. Let's fix that:
....
mixin display
  itemz { begin_with_general: 'it has a display', separator:',', last_separator:'and' }
    item
      | a physical size of #[+value(phone.displaySize)] inches
    item
      | a screen-to-body ratio of #[+value(phone.screenRatio)] %
....

include::partial$tuto_fragments.adoc[tag=begin_with_general_why]

You should get better texts: +
_The OnePlus 5T is really a fantastic phone. The phone's available tones are Black, Red and White. It has a display with a physical size of 6 inches and a screen-to-body ratio of 80.43 %._ +
_OnePlus 5: a great phone! The phone's available tones are Gold and Gray. It has a display with a physical size of 5.5 inches and a screen-to-body ratio of 72.93 %._ +
_OnePlus 3T: a great phone! The phone's available colors are Black, Gold and Gray. It has a display with a physical size of 5.5 inches and a screen-to-body ratio of 73.15 %._ +


You can add some diversity by randomly changing the order of the output by adding the `mix` parameter:
....
mixin display
  itemz { begin_with_general: 'it has a display', separator:',', last_separator:'and', mix:true }
    item
      | a physical size of #[+value(phone.displaySize)] inches
    item
      | a screen-to-body ratio of #[+value(phone.screenRatio)] %
....

_The OnePlus 5T is really a fantastic phone. The phone's available colors are Black, Red and White. It has a display with a screen-to-body ratio of 80.43 % and a physical size of 6 inches._ +
_The OnePlus 5 is really a fantastic phone. The phone's available tints are Gold and Gray. It has a display with a physical size of 5.5 inches and a screen-to-body ratio of 72.93 %._ +
_I really love the new OnePlus 3T. The phone's available colors are Black, Gold and Gray. It has a display with a physical size of 5.5 inches and a screen-to-body ratio of 73.15 %._

++++
<script>
const mixinDisplayString = `
mixin display
  itemz { begin_with_general: 'it has a display', separator:',', last_separator:'and', mix:true }
    item
      | a physical size of #[+value(phone.displaySize)] inches
    item
      | a screen-to-body ratio of #[+value(phone.screenRatio)] %
`;

const mixinPhone2String = `
mixin printPhone
  | #[+intro] .
  | #[+colors] .
  | #[+display] .
`;

spawnEditor(currentLang,
  main2String.replace('BEFORE', 
    [mixinColors2String, mixinDisplayString, mixinIntroString, mixinPhone2String].join('\n')
  ),
  'screen-to-body ratio of'
);
</script>
++++



== Even more variety

First let's add text some about the battery:
....
  | this phone has a battery of #[+value(phone.battery)] mAh .
....

Now we have a decent volume of text. But we would like to have more variability: we always talk about colors, the display, and the battery, in this order, but it could be in any order. Let's put all our text chunks in an `itemz > item` structure, and add a `mix`:
....
mixin phone_chunks
  itemz {separator: '.', end:'.', mix:true}
    item
      | #[+colors]
    item
      | #[+display]
    item
      | this phone has a battery of #[+value(phone.battery)] mAh

include::partial$tuto_en_US.pug[tags=phoneMixin]
....


++++
<script>
const mixinChunksString = `
mixin phone_chunks
  itemz {separator: '.', end:'.', mix:true}
    item
      | #[+colors]
    item
      | #[+display]
    item
      | this phone has a battery of #[+value(phone.battery)] mAh
`;

const mixinPhone3String = `
mixin printPhone
  | #[+intro] .
  | #[+phone_chunks]
`;

spawnEditor(currentLang,
  main2String.replace('BEFORE', [mixinColors2String, mixinDisplayString, mixinIntroString, mixinChunksString, mixinPhone3String].join('\n')),
  'screen-to-body ratio of'
);
</script>
++++


== Referring expressions

There is a hidden structure behind the way we talk about the phone :

* The first time we talk about it we use the name of the phone.
* The next times we use either `the phone`, `it`, or `this phone`.

include::partial$tuto_fragments.adoc[tag=refexpr_concept]

Let's create 2 mixins, one for each kind of representant:
....
mixin phone_ref(obj, params)
  | #{obj.name}

mixin phone_refexpr(obj, params)
  | #[+syn('the phone', 'this phone', 'it')]
....

TIP: The first parameter, `obj`, is the phone itself. `#{obj.name}` is exactly the same as `#{phone.name}`.

We also have to register them:
....
- let phone;
each phoneElt in phones
  - phone = phoneElt;
  
  p
    -
      phone.ref = phone_ref;
      phone.refexpr = phone_refexpr;
    | #[+printPhone]
....

Now we can use them everywhere:
....
mixin colors
  | #[+value(phone)]'s available #[+syn('colors', 'tints', 'tones')]
  | are
  ...

include::partial$tuto_en_US.pug[tags=introMixin]
....

In the `phone_chunks` mixin:
....
      | #[+value(phone)] has a battery of #[+value(phone.battery)] mAh
....

We have to change the structure for the `it has a display with`, as we cannot put a `value` directly in the `begin_with_general` structure. It has to be a string or a mixin:
....
include::partial$tuto_en_US.pug[tags=mixinItHasADisplay]
...
  itemz { begin_with_general: itHasADisplay, separator:',', last_separator:'and', mix:true }
....

This is what you should get: +
_OnePlus 5T: a great phone! It has a display with a physical size of 6 inches and a screen-to-body ratio of 80.43 %. It has a battery of 3300 mAh. It's available tones are Black, Red and White._ +
_I really love the new OnePlus 5. This phone has a display with a physical size of 5.5 inches and a screen-to-body ratio of 72.93 %. The phone has a battery of 3300 mAh. This phone's available tints are Gold and Gray._ +
_The OnePlus 3T is really a fantastic phone. This phone's available colors are Black, Gold and Gray. It has a display with a physical size of 5.5 inches and a screen-to-body ratio of 73.15 %. This phone has a battery of 3400 mAh._


++++
<script>

const main3String = mainString.replace('MAIN', 
`
  p
    -
      phone.ref = phone_ref;
      phone.refexpr = phone_refexpr;
    | #[+printPhone]
`);

const mixinPhoneRefRefexprString = `
mixin phone_ref(obj, params)
  | #{obj.name}

mixin phone_refexpr(obj, params)
  | #[+syn('the phone', 'this phone', 'it')]
`;

const mixinColors3String =
`mixin colors
  | #[+value(phone)]'s available #[+syn('colors', 'tints', 'tones')]
  | are
  eachz color in phone.colors with { separator:',', last_separator:'and', end:'.' }
    | #{color}
`;

const mixinIntro3String = `
mixin intro
  synz
    syn
      | the #[+value(phone)] is really a fantastic phone.
    syn
      | i really love the new #[+value(phone)].
    syn
      | #[+value(phone)] : a great phone !
`;

const mixinChunks2String = `
mixin phone_chunks
  itemz {separator: '.', end:'.', mix:true}
    item
      | #[+colors]
    item
      | #[+display]
    item
      | #[+value(phone)] has a battery of #[+value(phone.battery)] mAh
`;

const mixinDisplay2String = `
mixin itHasADisplay
  | #[+value(phone)] has a display with

mixin display
  itemz { begin_with_general: itHasADisplay, separator:',', last_separator:'and', mix:true }
    item
      | a physical size of #[+value(phone.displaySize)] inches
    item
      | a screen-to-body ratio of #[+value(phone.screenRatio)] %

`;

spawnEditor(currentLang,
  main3String.replace('BEFORE', [mixinColors3String, mixinDisplay2String, mixinIntro3String, mixinChunks2String, mixinPhoneRefRefexprString, mixinPhone3String].join('\n')),
  'has a display with'
);
</script>
++++

It's pretty decent, but there's one issue: you can trigger _It's available tones are_ which is wrong. It should be either _the phone's_, _this phone's_, or _its_.



== Conditional texts

We could use different techniques to address that, but a pretty straightforward solution is just to forbid the use of `it` at this specific place.

Let's add a flag when calling the referring expression: we just don't want _it_ to be triggered:
....
include::partial$tuto_en_US.pug[tags=colorsMixinNotIt]
....

Now we have to:

* catch this flag in our referring expression mixin
* use the `synz > syn` structure instead of `syn` to be able to write the condition

....
mixin phone_refexpr(obj, params)
  synz
    syn
      | the phone
    syn
      | this phone
    syn
      if !hasFlag(params, 'NOT_IT')
        | it
....

Generate the texts and you should see that the _It's_ have disappeared.


++++
<script>
const mixinPhoneRefRefexpr2String = `
mixin phone_ref(obj, params)
  | #{obj.name}

mixin phone_refexpr(obj, params)
  synz
    syn
      | the phone
    syn
      | this phone
    syn
      if !hasFlag(params, 'NOT_IT')
        | it
`;

const mixinColors4String =
`mixin colors
  | #[+value(phone, {'NOT_IT':true})]'s available #[+syn('colors', 'tints', 'tones')]
  | are
  eachz color in phone.colors with { separator:',', last_separator:'and', end:'.' }
    | #{color}
`;

spawnEditor(currentLang,
  main3String.replace('BEFORE', [mixinColors4String, mixinDisplay2String, mixinIntro3String, mixinChunks2String, mixinPhoneRefRefexpr2String, mixinPhone3String].join('\n')),
  'OnePlus'
);
</script>
++++


include::partial$tuto_fragments.adoc[tag=empty_synonym]

Still we can have this kind of output: +
_The OnePlus 5T is really a fantastic phone. This phone has a display with a screen-to-body ratio of 80.43 % and a physical size of 6 inches. This phone's available tints are Black, Red and White. This phone has a battery of 3300 mAh._

We have 3 times _This phone_ here which is not perfect. How could we avoid that?

== Change synonym mode

Instead of choosing synonyms randomly, we can just trigger them in sequence. This will avoid close repetitions:
....
mixin phone_refexpr(obj, params)
  synz {mode:'sequence'}
    syn
      ...
....

Now we should have less repetitions in our synonyms for the phone.


++++
<script>
const mixinPhoneRefRefexpr3String = `
mixin phone_ref(obj, params)
  | #{obj.name}

mixin phone_refexpr(obj, params)
  synz {mode:'sequence'}
    syn
      | the phone
    syn
      | this phone
    syn
      if !hasFlag(params, 'NOT_IT')
        | it
`;

spawnEditor(currentLang,
  main3String.replace('BEFORE', [mixinColors4String, mixinDisplay2String, mixinIntro3String, mixinChunks2String, mixinPhoneRefRefexpr3String, mixinPhone3String].join('\n')),
  'he phone'
);
</script>
++++

== Fancier sentences and "has said"

Let's generate a fancier sentence combining display size and battery capacity: _The phone has a display with a screen-to-body ratio of 73.15 % and a physical size of 5.5 inches along with a battery of 3400 mAh._

This is quite straightforward:
....
| #[+display]
| along with a battery of #[+value(phone.battery)] mAh
....

The problem is, _we don't want to talk about the battery twice_. We could just remove the standard battery sentence (_The phone has a battery of 3400 mAh_), but let's try to *trigger the battery sentence only if we have not talked about the battery before*. This is where `hasSaid` and `recordSaid` come in.

....
include::partial$tuto_en_US.pug[tags=hasSaid]
....

include::partial$tuto_fragments.adoc[tag=has_said_solution]


You should get those nice sentences:+
_OnePlus 5T: a great phone! The phone has a battery of 3300 mAh. This phone's available tints are Black, Red and White. It has a display with a physical size of 6 inches and a screen-to-body ratio of 80.43 %._ +
_OnePlus 5: a great phone! The phone has a battery of 3300 mAh. This phone has a display with a physical size of 5.5 inches and a screen-to-body ratio of 72.93 %. The phone's available colors are Gold and Gray._



++++
<script>
const mixinChunks3String = `
mixin phone_chunks
  itemz {separator: '.', end:'.', mix:true}
    item
      | #[+colors]
    item
      | #[+display]
      
      if !hasSaid('BATTERY')
        | along with a battery of #[+value(phone.battery)] mAh
        recordSaid('BATTERY')
    item
      if !hasSaid('BATTERY')
        | #[+value(phone)] has a battery of #[+value(phone.battery)] mAh
        recordSaid('BATTERY')
`;

const main4String = mainString.replace('MAIN', 
`
  p
    -
      phone.ref = phone_ref;
      phone.refexpr = phone_refexpr;
    | #[+printPhone]
    deleteSaid('BATTERY')
`);

spawnEditor(currentLang,
  main4String.replace('BEFORE', [mixinColors4String, mixinDisplay2String, mixinIntro3String, mixinChunks3String, mixinPhoneRefRefexpr3String, mixinPhone3String].join('\n')),
  'a battery'
);
</script>
++++



include::partial$tuto_fragments.adoc[tag=congrats]

== Even more

We have gone through some aspects of NLG with this tutorial. 

There are some other features you can explore, for instance:

* automatic a / an : `a apple` => `an apple`, `a hour` => `an hour`
* agreement of verbs (especially the irregular ones)
* agreement of words: `tomato` => `tomatoes`
* etc.


== Final version of the code

`tuto.js`
[source,javascript]
[subs=attributes+]
....
include::partial$tuto_fragments.js[tags=require]
include::partial$tuto_fragments.js[tags=data]
include::partial$tuto_fragments.js[tags=mainLoop]
....

`tuto.pug`
....
include::partial$tuto_en_US.pug[]
....
