= Agreement of nouns and adjectives

== Substantive (or how to agree words)

`substantive(word, agreeWith)` will agree the word (with is just a noun) with `agreeWith`.

For instance:
++++
<script>
spawnEditor('en_US', 
`-
  var DIAMONDS = {bla: 'bla'};
  setRefNumber(DIAMONDS, 'P');

p #[+substantive("diamond", DIAMONDS)]
`, 'iamonds'
);
</script>
++++
This will output _diamonds_.

Works in `en_US`, `fr_FR`, `de_DE` and `it_IT`.

anchor:agree_adjectives[agree adjectives]

== Agree adjectives with `agreeAdj`

Use `agreeAdj(adjective, subject)` to agree an `adjective` with a `subject`.

For instance in `fr_FR`:
++++
<script>
spawnEditor('fr_FR', 
`p #[+agreeAdj('luxueux', getAnonFP())] / #[+agreeAdj('muni', getAnonFP())]
`, 'uxueuses / munies'
);
</script>
++++
will output _luxueuses / munies_.

In German you have to indicate both the case and the determiner:
++++
<script>
spawnEditor('de_DE', 
`p der #[+agreeAdj('alt', 'Gurke', {case:'GENITIVE', det:'DEFINITE'})] Gurke
p #[+value('Gurke', {case:'GENITIVE', det:'DEFINITE', adj:'alt'})]
`, 'er alten Gurke'
);
</script>
++++
will output _der alten Gurke_.

TIP: You can also use `value` with the `adj` property. `p #[+value('Gurke', {case:'GENITIVE', det:'DEFINITE', adj:'alt'})]` will also output _der alten Gurke_.

++++
<script>
spawnEditor('it_IT', 
`p la #[+agreeAdj('vecchio', 'casa')] casa
`, 'a vecchia casa'
);
</script>
++++
will output _la vecchia casa_.
