= Recording what was said for further use

== `recordSaid`, `hasSaid` and `deleteSaid`

Sometimes you need to record what you just said to keep that information for the upcoming texts. For instance you mention the brand of the product in some mixin, and you have another mixin which can also trigger the brand: you might only want to output the brand once.

You might wonder why you can not just use global variables to record what was said. The problem is that RosaeNLG needs to go back and forth in the text generation (typically to predict which synonymic alternatives are empty), and this means that you must not use global variables to record what was said, because RosaeNLG will not be able to rollback after a synonym simulation.

Thus you should use `recordSaid` and `hasSaid`. They basically only are accessors to an internal map, which is properly rollbacked when necessary.

++++
<script>
spawnEditor('en_US', 
`mixin brand
  if !hasSaid('BRAND')
    | brand is myBrand
    recordSaid('BRAND')

p #[+brand] #[+brand]
`, 'rand is myBrand'
);
</script>
++++
This will only output _brand is ..._ once.

Reference:

* `recordSaid(key)`: to record that something was said.
* `hasSaid(key)`: returns a boolean indicating if something was said.
* `deleteSaid(key)`: forget that something was said.
* `dumpHasSaid` to console output what is in the internal map.

TIP: You can use `recordSaid('BRAND')` or `- recordSaid('BRAND');` - it is the same.


== `recordValue`, `getValue` and `deleteValue`

Behind the scenes, `recordSaid`, `hasSaid` and `deleteSaid` store booleans in a managed hashmap. You can use the same hashmap to store values. Typically you could count how many times you have talked about something.

* `recordValue(key, val)` records a value for a given key
* `getValue(key)` returns the stored value for a key
* `deleteValue(key)` to delete a key

++++
<script>
spawnEditor('en_US', 
`mixin product
  if getValue('SAID_PRODUCT') < 2
    | product
    recordValue('SAID_PRODUCT', getValue('SAID_PRODUCT')+1)
  else
    | something else

recordValue('SAID_PRODUCT', 0)
p #[+product] #[+product] #[+product] #[+product]
`, 'roduct product something'
);
</script>
++++
This will only output _product_ twice.


WARNING: You can only store numbers or strings, but not complex objects.
