= Client side in browser compiling and rendering

Both compilation and rendering are made in the browser: templates can be authored directly in the browser, or dynamically generated, compiled in the browser and the texts can also be rendered in the browser.

To be able to do that, you must use a js version of freeNLG that is larger, with `_comp` at the end, like `freenlg_tiny_fr_FR_*_comp.js`:

* it includes the templates compiler
* but also all linguistic resources that are associated with a language

TIP: Client side compilation is for exotic usecases. You should favor server side compilation.

It can be used to create a 100% client side editor and renderer, link:https://freenlg.org/secret/ide/demo_en_US.html[like in this demo].

TIP: For a complete technical POC that effectively generates texts in a browser using FreeNLG, see separate repo `freenlg-browser-poc`.

== Packaged version of FreeNLG for client side usage

FreeNLG provides browser ready "tinyified" packages per language in `dist/browser`:

.Available packages per language
[options="header"]
|=======================================================
Language | Compilation  | Rendering | Size (approx.)
| `en_US` | no  | yes | 801 Kb
| `fr_FR` | no  | yes | 609 Kb
| `de_DE` | no  | yes | 570 Kb
| `it_IT` | no  | yes | 558 Kb
| `OTHER` | no  | yes | 515 Kb
| `en_US` | yes | yes | 1 789 Kb
| `fr_FR` | yes | yes | 8 725 Kb
| `de_DE` | yes | yes | 54 764 Kb
| `it_IT` | yes | yes | 3 434 Kb
| `OTHER` | yes | yes | 1 514 Kb
|=======================================================

CAUTION: Well, the German version with compilation support is too large indeed.

