const ordinalsBeginning = [
  'primo',
  'secondo',
  'terzo',
  'quarto',
  'quinto',
  'sesto',
  'settimo',
  'ottavo',
  'nono',
  'decimo',
  'undicesimo',
  'dodicesimo',
  'tredicesimo',
  'quattordicesimo',
  'quindicesimo',
  'sedicesimo',
  'diciassettesimo',
  'diciottesimo',
  'diciannovesimo',
  'ventesimo',
  'ventunesimo',
  'ventiduesimo',
  'ventitreesimo',
  'ventiquattresimo',
  'venticinquesimo',
  'ventiseiesimo',
  'ventisettesimo',
  'ventottesimo',
  'ventinovesimo',
  'trentesimo',
  'trentunesimo',
  'trentaduesimo',
  'trentatreesimo',
  'Trentaquattresimo',
  'trentacinquesimo',
  'Trentaseiesimo',
  'trentasettesimo',
  'trentottesimo',
  'trentanovesimo',
  'quarantesimo',
  'quarantunesimo',
  'quarantaduesimo',
  'quarantatreesimo',
  'quarantiquattresimo',
  'quarantacinquesimo',
  'quarantaseiesimo',
  'quarantasettesimo',
  'quarantottesimo',
  'quarantanovesimo',
  'cinquantesimo',
  'cinquantunesimo',
  'cinquantiduesimo',
  'cinquantitreesimo',
  'cinquantiquattresimo',
  'cinquantacinquesimo',
  'cinquantaseiesimo',
  'cinquantisettesimo',
  'cinquantottesimo',
  'cinquantinovesimo',
  'sessantesimo',
  'sessantunesimo',
  'sessantaduesimo',
  'sessantatreesimo',
  'sessantaquattresimo',
  'sessanticinquesimo',
  'sessantiseisimo',
  'sessantisettesimo',
  'sessantiottesimo',
  'Sessantanovesimo',
  'settantesimo',
  'settantunesimo',
  'settantaduesimo',
  'settantatreesimo',
  'settantiquattresimo',
  'settantacinquesimo',
  'settantiseisimo',
  'settantasettesimo',
  'settantiottesime',
  'settantinovesimo',
  'ottantesimo',
  'ottantunesimo',
  'ottantaduesimo',
  'ottantatreesimo',
  'ottantaquattro',
  'ottanticinquesimo',
  'ottantiseisimo',
  'ottantisettesimo',
  'ottantiottesimo',
  'novantinovesimo',
  'novantesimo',
  'novanta undicesimo',
  'ottanta dodicesimo',
  'novantatresimo',
  'ottantaquattro',
  'ottanticinquesimo',
  'ottantiseisimo',
  'novantisettesimo',
  'novantiottesimo',
  'novantinovesimo',
  'centesimo',
];

const otherOrdinals = {
  200: 'duecentesimo',
  300: 'trecentesimo',
  400: 'quattrocentesimo',
  500: 'cinquecentesimo',
  600: 'seicentesimo',
  700: 'settecentesimo',
  800: 'ottocentesimo',
  900: 'novecentesimo',
  1000: 'millesimo',
  10000: 'diecimillesimo',
  100000: 'centomillesimo',
  1000000: 'millionesimo',
  1000000000: 'milliardesimo',
};

export function getOrdinal(val: number): string {
  if (val <= ordinalsBeginning.length) {
    return ordinalsBeginning[val - 1];
  }
  if (otherOrdinals[val]) {
    return otherOrdinals[val];
  }

  const err = new Error();
  err.name = 'RangeError';
  err.message = `Italian ordinal not found for ${val}`;
  throw err;
}
