= Other structures, mixins and functions

== Structures

`titlecase` will capitalize the first letter of the _main_ words in its content (which is surprisingly more subtle than just uppercasing each word).

It uses these libs:

* in English: link:https://www.npmjs.com/package/titlecase[titlecase on npm]
* in French: link:https://www.npmjs.com/package/titlecase-french[titlecase-french on npm]

Not available in German.

There are plenty of options for each of these libs, but they are not supported by FreeNLG yet (you get the default output).

== Mixins

* `isSentenceStart()` will return a true if you are at the very beginning of a sentence (i.e. no word has been output yet). Use the `#[+flushBuffer]` mixin just before to be sure that `isSentenceStart()` returns a valid value.
* `toHtmlList(obj)` will generate an HTML structure of the js object, with `<ul>` and `<li>` etc. This is useful for outputting the data that was used to generate a text, in the same document.
* `uppercaseWords(str)` will output all words of the string with the first letter uppercase.
* `eatSpace` will 'eat' the spaces around him. `bla #[+eatSpace()] bla` outputs `blabla`.

== Functions

* `getRefGender(obj)` gives the current gender of an object (according to the last triggered representant). It should not be used that often.
* `getRefNumber(obj)` give the current number of an object.
* `getSorP(table, obj)`: `table` is an array with 2 elements. If `obj` is singular, the first item of the array will be output, if plural, it will be the second. It can be useful in xref:referring_expression.adoc[referring expressions]: `#{getSorP(['it', 'they'], DIAMOND)}`
* `getMFN(table, obj)`: same as `getSorP` but for masculine/feminine/neutral. You don't need to provide a neutral if it does not exist in the target language. `getMorF(table, obj)` is an alias.
* `valueToSorP(val)` will return 'S' (singular) if `val` is > 1 and 'P' (plural) otherwise. Useful in xref:referring_expression.adoc[referring expressions] when the number can vary: `setRefNumber(DIAMONDS, valueToSorP(DIAMONDS.numberOfDiamonds));`
* `logParams(params)` will put in console the stringified param object.
* `util.compromise` give a direct access to link:http://compromise.cool/[compromise lib]. `#{ util.compromise('London is calling').sentences().toNegative().out() }` will output _London is not calling_.

