site:
  title: RosaeNLG // Docs
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://rosaenlg.github.io/rosaenlg
  start_page: rosaenlg:ROOT:index.adoc
content:
  sources:
  # new pattern, all new versions, excluding old ones
  - url: ../..
    branches: [v*.*.*, '!v1.*.*', '!v2.*.*']
    start_path: packages/rosaenlg-doc/doc
ui:
  bundle:
    url: ../rosaenlg-antora-ui/build/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: ./gh-pages
antora:
  extensions:
  - require: '@antora/lunr-extension'
