site:
  title: RosaeNLG // Docs
  url: https://rosaenlg.org
  start_page: rosaenlg:ROOT:index.adoc
content:
  sources:
  - url: ../..
    branches: [v4.2.0, v4.0.0, v3.3.0, v2.1.8]
    start_path: packages/rosaenlg-doc/doc
ui:
  bundle:
    url: ../rosaenlg-antora-ui/build/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: ./local
antora:
  extensions:
  - require: '@antora/lunr-extension'

