// Copyright 2020 Ludan Stoecklé
// SPDX-License-Identifier: Apache-2.0
= Debugging

To properly set parameters, check xref:advanced:params.adoc[global parameters doc].

== Show line when fails: compileDebug

*Put `compileDebug: true` when compiling the template (it is the default value). When an exception occurs, the error message will mention the original template filename and the line.*

The templates are transformed in plain JavaScript before rendering can occur. Therefore, when an exception or an error occurs during rendering, the JavaScript line number is generally not meaningful: what is useful is the line number of the original template (and its filename).
`compileDebug: true` generates extra lines in the generated JavaScript code to map with the original template filename and line number.

TIP: As it adds extra lines of debug code for each generated line, it should be disabled for production.


== See where a specific text has been generated 

Sometimes you need to know exactly where a specific text present in the output comes from.
*When rendering, put `renderDebug` to `true` to see the exact path followed in the templates.*

- it will log each mixin it goes through, even when finally proven empty, thus expect some verbosity
- the path will be the good one, but the generated text will contain filtering issues: contractions not done, wrong capitalization, missing punctuation
- `renderDebug` is a rendering parameter, but it only works when `compileDebug` was `true` when compiling


Sample output (on English tutorial):
----
tuto_en_US.pug: 52
tuto_en_US.pug: 60
tuto_en_US.pug: 62
The phone
tuto_en_US.pug: 52
Has a battery of
tuto_en_US.pug: 52
3,300
tuto_en_US.pug: 52
MAh
tuto_en_US.pug: 53
tuto_en_US.pug: 42
tuto_en_US.pug: 42
tuto_en_US.pug: 16
tuto_en_US.pug: 16
tuto_en_US.pug: 60
tuto_en_US.pug: 64
This phone 
----

TIP: When debugging, use it along `randomSeed` so that the generated text remains the same at each run.

To have a more readable output, consider using css:
[source,css]
----
.debug {
  font-size: xx-small;
  font-family: monospace;
}
----

