// Copyright 2019 Ludan Stoecklé
// SPDX-License-Identifier: CC-BY-4.0
= Possessives with `recipientPossession` and `thirdPossession`

_not available in Italian and Spanish yet_

anchor:thirdPossession[thirdPossession]

== With `thirdPossession`

Use it when you want to talk of a property of an object. If the object you talk about is a ring, you may want to talk about its weight, its size, etc. - texts like _the weight of the ring_, _its size_, etc.

Use `thirdPossession(owner, owned)`:
++++
<script>
spawnEditor('fr_FR', 
`- var BAGUE = {};
mixin bague_ref(obj, params)
  | #[+value('bague', {represents:BAGUE, det:'DEFINITE'})]
- BAGUE.ref = bague_ref;

p #[+thirdPossession(BAGUE, 'largeur')] / #[+thirdPossession(BAGUE, 'poids')]
`, 'a largeur de la bague / son poids'
);
</script>
++++
will output _la largeur de la bague / son poids_.

As usual `thirdPossession` takes an optional last parameter that is sent as is to the subject.

In English you can add `possForm`: `OF` (default) to generate texts like _the width of the ring_ or `S` for _the ring's width_.

WARNING: in *English*, you have to indicate the gender of the owner, using `setRefGender`, as it has no built-in dictionnary. `woman`, `actress`, `widow` etc. are Feminine, `man` etc. are Masculine, while `ring` is neutral:
++++
<script>
spawnEditor('en_US', 
`
- const RING = {};
mixin ring_ref(obj, params)
  | #[+value('ring', {det:'DEFINITE'})]
  - setRefGender(obj, 'N');
- RING.ref = ring_ref;
p #[+thirdPossession(RING, 'width')] / #[+thirdPossession(RING, 'width')]
`, 'he width of the ring / its width'
);
</script>
++++
will output _the width of the ring / its width_ - but `- setRefGender(obj, 'N');` is mandatory.

In *German* you can indicate the case:
++++
<script>
spawnEditor('de_DE', 
`
- var PRODUKT = {};
mixin produkt_ref(obj, params)
  | #[+value('Gurke', addToParams({represents: PRODUKT, 'det': 'DEFINITE'}))]
- PRODUKT.ref = produkt_ref;

p
  | #[+value(PRODUKT)] :
  | 8 cm ist #[+thirdPossession(PRODUKT, 'Durchmesser', {case:'GENITIVE'})] ,
  | grün ist #[+thirdPossession(PRODUKT, 'Farbe', {case:'GENITIVE'})]
`, 'ie Gurke: 8 cm ist ihres Durchmessers, grün ist ihrer Farbe'
);
</script>
++++
will output: _die Gurke: 8 cm ist ihres Durchmessers, grün ist ihrer Farbe_.

`addToParams` is required here so that the case is conveyed through the call stack.

TIP: You can use `value` with `owner` param instead of `thirdPossession`. `&#35;[+value('largeur', {owner: BAGUE})]` is equivalent to `&#35;[+thirdPossession(BAGUE, 'largeur')]`.


== With `recipientPossession`

_French and English only (partial support for both)_

`recipientPossession(owned)` will output item as if owned by the reader. `&#35;[+recipientPossession(PRODUCT)]` will output _votre bague_ or _vos boucles d'oreille_.

++++
<script>
spawnEditor('fr_FR', 
`
- var BAGUE = {};
mixin bague_ref(obj, params)
  | #[+value('bague', {represents:BAGUE})]
- BAGUE.ref = bague_ref;

p #[+recipientPossession(BAGUE)]
`, 'Votre bague'
);
</script>
++++
