= Sentences for French

== Examples

++++
<script>
spawnEditor('fr_FR', 
`- const SUJET_JARDINIER = {};
mixin SUJET_JARDINIER_ref(obj, params)
  | le jardinier
  - setRefNumber(SUJET_JARDINIER, 'S');
  - setRefGender(SUJET_JARDINIER, 'jardinier');
- SUJET_JARDINIER.ref = SUJET_JARDINIER_ref;

mixin SUJET_JARDINIER_refexpr(obj, params)
  | il
- SUJET_JARDINIER.refexpr = SUJET_JARDINIER_refexpr;

- const COD_POMMES = {};
mixin COD_POMMES_ref(obj, params)
  | des pommes
  - setRefGender(COD_POMMES, 'pomme');
  - setRefNumber(COD_POMMES, 'P');
- COD_POMMES.ref = COD_POMMES_ref;

- const COI_VOISINE = {};
mixin COI_VOISINE_ref(obj, params)
  | sa voisine
  - setRefNumber(COI_VOISINE, 'S');
  - setRefGender(COI_VOISINE, 'voisine');
- COI_VOISINE.ref = COI_VOISINE_ref;

-
  const sentencePommes = {
    subjectGroup: {
      subject: SUJET_JARDINIER,
    },
    verbalGroup: {
      verb: 'donner',
      tense: 'PASSE_COMPOSE',
      aux:'AVOIR',
    },
    objGroups: [
      {
        type: 'DIRECT',
        obj: COD_POMMES,
      },
      {
        type: 'INDIRECT',
        preposition: 'à',
        obj: COI_VOISINE,
      },
    ]
  };

p
  | #[+sentence(sentencePommes)].
  | #[+sentence(sentencePommes)].

  //- only COI pronoun
  - resetRep(COD_POMMES);
  | #[+sentence(sentencePommes)].

  //- only COD pronoun
  - resetRep(COI_VOISINE);
  | #[+sentence(sentencePommes)].
`, 'Le jardinier a donné des pommes à sa voisine. Il les lui a données. Il lui a donné des pommes. Il les a données à sa voisine.'
);
</script>
++++
will generate:

* _Le jardinier a donné des pommes à sa voisine._
* _Il les lui a données._
* _Il lui a donné des pommes._
* _Il les a données à sa voisine._

== Features and Usage

The generation order between `DIRECT` and `INDIRECT` respects the declared order: if you change the order, you can generate _Le jardinier a donné à sa voisine des pommes_.

Use `negative: true` and optionnaly `negativeAdverb` (e.g. `jamais`, will default to `pas`) to generate a negative form, like _Il ne les lui a pas données._.

Agreement with direct complement when using `avoir` auxiliary is made automatically.

There can be 2 indirect object groups, for instance to generate _Pascal parle à son frère de sa leçon_ / _Il lui parle de sa leçon_. Put multiple objects with type `INDIRECT` in the `objGroups` array.

In `subjectGroup`, use `person` to generate a personal subject pronoun (_je, tu, nous, vous, etc._). Possible values are `1S` (1st person, singular => _je_), `2S`, `1P`, `2P` (2nd person, plural => _vous_) as possible values. `3S` and `3P` are not allowed as we would not know whether to generate _il/elle_ or _ils/elles_. When using `person` parameter, `subject` property is ignored.


TODO: _il lui en parle_ is not supported.

You can also add the usual value parameters to the `subjectGroup` and `objGroups`

== Examples

++++
<script>
spawnEditor('fr_FR', 
`
- const SUJET_FEMME = {};
mixin SUJET_FEMME_ref(obj, params)
  | #[+value('femme', params )]
  - setRefNumber(SUJET_FEMME, 'S');
  - setRefGender(SUJET_FEMME, 'femme');
- SUJET_FEMME.ref = SUJET_FEMME_ref;

mixin SUJET_FEMME_refexpr(obj, params)
  | elle
- SUJET_FEMME.refexpr = SUJET_FEMME_refexpr;

- const COD_TONDEUSE = {};
mixin COD_TONDEUSE_ref(obj, params)
  | #[+value('tondeuse', params )]
  - setRefGender(COD_TONDEUSE, 'tondeuse');
  - setRefNumber(COD_TONDEUSE, 'S');
- COD_TONDEUSE.ref = COD_TONDEUSE_ref;

- const COI_NEVEU = {};
mixin COI_NEVEU_ref(obj, params)
  | #[+value('neveu', params )]
  - setRefNumber(COI_NEVEU, 'S');
  - setRefGender(COI_NEVEU, 'neveu');
- COI_NEVEU.ref = COI_NEVEU_ref;

-
  const sentenceTondeuse = {
    subjectGroup: {
      subject: SUJET_FEMME,
      params: {det:'POSSESSIVE' , personOwner: 2}
    },
    verbalGroup: {
      verb: 'prêter',
      tense: 'PASSE_COMPOSE',
      aux:'AVOIR',
    },
    objGroups: [
      {
        type: 'DIRECT',
        obj: COD_TONDEUSE ,
        params: {det:'POSSESSIVE', personOwner: 1}
      },
      {
        type: 'INDIRECT',
        preposition: 'à',
        obj: COI_NEVEU,
        params: {det:'POSSESSIVE', personOwner: 3}
      },
    ]
  };

p
  | #[+sentence(sentenceTondeuse)].
  | #[+sentence(sentenceTondeuse)].
`, 'Ta femme a prêté ma tondeuse à son neveu. Elle la lui a prêtée.'
);
</script>
++++
will generate:

* _Ta femme a prêté ma tondeuse à son neveu._
* _Elle la lui a prêtée._

