= Sentences for English

== Examples

++++
<script>
spawnEditor('en_US', 
`- const SUBJECT_GARDENER = {};
mixin SUBJECT_GARDENER_ref(obj, params)
  | the gardener
  - setRefNumber(SUBJECT_GARDENER, 'S');
  - setRefGender(SUBJECT_GARDENER, 'M');
- SUBJECT_GARDENER.ref = SUBJECT_GARDENER_ref;

mixin SUBJECT_GARDENER_refexpr(obj, params)
  | he
- SUBJECT_GARDENER.refexpr = SUBJECT_GARDENER_refexpr;

- const DIRECTOBJ_APPLES = {};
mixin DIRECTOBJ_APPLES_ref(obj, params)
  | apples
  - setRefNumber(DIRECTOBJ_APPLES, 'P');
- DIRECTOBJ_APPLES.ref = DIRECTOBJ_APPLES_ref;

- const INDIRECTOBJ_NEIGHBOR = {};
mixin INDIRECTOBJ_NEIGHBOR_ref(obj, params)
  | the neighbor
  - setRefNumber(INDIRECTOBJ_NEIGHBOR, 'S');
  - setRefGender(INDIRECTOBJ_NEIGHBOR, 'F');
- INDIRECTOBJ_NEIGHBOR.ref = INDIRECTOBJ_NEIGHBOR_ref;

-
  const sentenceApples = {
    subjectGroup: {
      subject: SUBJECT_GARDENER,
    },
    verbalGroup: {
      verb: 'give',
      tense: 'PAST',
    },
    objGroups: [
      {
        type: 'DIRECT',
        obj: DIRECTOBJ_APPLES,
      },
      {
        type: 'INDIRECT',
        obj: INDIRECTOBJ_NEIGHBOR,
      },
    ],
  };

p
  | #[+sentence(sentenceApples)].
  | #[+sentence(sentenceApples)].
  - resetRep(DIRECTOBJ_APPLES);
  | #[+sentence(sentenceApples)].
  - resetRep(INDIRECTOBJ_NEIGHBOR);
  | #[+sentence(sentenceApples)].
`, 'The gardener gave apples to the neighbor. He gave them to her. He gave apples to her. He gave them to the neighbor.'
);
</script>
++++
will generate:

* _The gardener gave apples to the neighbor._
* _He gave them to her._
* _He gave apples to her._
* _He gave them to the neighbor._

== Features and Usage

The generation order between `DIRECT` and `INDIRECT` respects the declared order.

Use `negative: true` to generate a negative form, like _he didn't give..._. In the negative form, you can also use:

* `contractNegation` to indicate whether do use the contracted form (e.g. _did not => didn't_). Default is `false` (no contraction).
* when the verb is `have`, you can add `negationNoDo: true` to remove to `do` and use the negative form of `have`: e.g. _she does not have it_ => _she hasn't it_. Please note that contraction is always on in this case: _she has not it_ is not valid.

++++
<script>
spawnEditor('en_US', 
`- const NEIGHBOR = {};
mixin NEIGHBOR_ref(obj, params)
  | the neighbor
  - setRefNumber(NEIGHBOR, 'S');
  - setRefGender(NEIGHBOR, 'F');
- NEIGHBOR.ref = NEIGHBOR_ref;

mixin NEIGHBOR_refexpr(obj, params)
  | she
- NEIGHBOR.refexpr = NEIGHBOR_refexpr;

- const CHOCOLATE = {};
mixin CHOCOLATE_ref(obj, params)
  | a chocolate bar
  - setRefNumber(CHOCOLATE, 'S');
  - setRefGender(CHOCOLATE, 'N');
- CHOCOLATE.ref = CHOCOLATE_ref;

-
  const sentenceHasSomething = {
    subjectGroup: {
      subject: NEIGHBOR,
    },
    negative: true,
    verbalGroup: {
      verb: 'have',
      tense: 'PRESENT',
    },
    objGroups: [
      {
        type: 'DIRECT',
        obj: CHOCOLATE,
      },
    ],
  };

p
  | #[+sentence(sentenceHasSomething)].
  | #[+sentence(sentenceHasSomething)].
  - sentenceHasSomething.negationNoDo = true;
  | #[+sentence(sentenceHasSomething)].

`, 'The neighbor does not have a chocolate bar. She does not have it. She hasn\'t it.'
);
</script>
++++
will generate: _The neighbor does not have a chocolate bar. She does not have it. She hasn't it._
