// Copyright 2019 Ludan Stoecklé
// SPDX-License-Identifier: CC-BY-4.0
= Value for Nominal Groups
 
`value` is used to generate nominal groups: determiners, adjectives, nouns, plurals, etc.

Structure:

* The first parameter of the tag is always the noun (or a list of nouns, see further)
* The second parameter is a structured object with many optional keys, like `det` to indicate a determiner

For instance, `\#[+value('homme', {det:'INDEFINITE', adj:'vieux', adjPos:'BEFORE'})]` will generate _un vieil homme_.

If there is only the first parameter (a string), and nothing else, the string will be output as is. In necessary you can protect from inappropriate capitalization and contraction using `protectString`.

== Determiners

Use `det` key to add a determiner. Available determiners are `DEFINITE`, `INDEFINITE`, `DEMONSTRATIVE` and `POSSESSIVE`.

Some languages have multiple distance levels for `DEMONSTRATIVE`. Use the additional key `dist`:

* in English and Italian, use `NEAR` (default) for this/these (in English) and `FAR` for that/those (in English)
* in Spanish, use `PROXIMAL`, `MEDIAL` or `DISTAL`

In English, when determiner is `DEFINITE` and number is plural, it will by default generate no article (_machines_). To trigger the article, put the `useTheWhenPlural` to `true`: `\#[+value('machine', {det:'DEFINITE', number:'P', useTheWhenPlural: true})]` will output _the machines_.

In French, when determiner is `INDEFINITE` and number is plural _and_ there is an adjective before the noun, _de_ will be output instead of _des_: _de bons restaurants_. To disable this mechanism, use `FORCE_DES`: `\#[+value('service', {det:'INDEFINITE', adj:'nouveau', adjPos:'BEFORE', number:'P', FORCE_DES: true})]` will output _des bons restaurants_.

TIP: In rare cases, you might want to generate only the determiner: `\#[+value('', {det:'DEFINITE', gender:'M', number:'S'})]`.


== Adjectives

One or multiple adjectives can be added and agreed automatically.

Apocope and specific cases are managed, like _gran árbol_ in Spanish, _vieil homme_ in French, etc.


=== One single adjective

If you wish to add only one single adjective, use the `adj` key. For instance `\#[+value('house', { det:'DEFINITE', adj:'white'})]` will generate _the white house_.

In some languages, like English, the adjective is always put before the noun. In some others, like French, it is often placed after (_les gâteaux délicieux_), but can also be placed before (_les bons gâteaux_). Set `adjPos` to `BEFORE` or `AFTER` to change the position of the adjective.

.Adjective position
[options="header"]
|=========================================================
| Language | Default | Can be changed using `adjPos`
| `en_US` | before | no
| `de_DE` | before | no
| `es_ES` | after | yes
| `fr_FR` | after | yes
| `it_IT` | after | yes
|=========================================================

In French, `\#[+value('affaire', {det:'INDEFINITE', adj:'sale', adjPos:'BEFORE', number:'P'})]` will generate _des sales affaires_.


=== Multiple adjectives

Same structure but with a table e.g. `adj:['nice','big']`. `adjPos` remains valid.


=== Multiple adjectives, some before, some after

When you wish to have some adjectives before the noun and some other adjectives after, you can use the full form with `BEFORE` and `AFTER`: in French, `\#[+value('vache', {det:'INDEFINITE', adj:{ BEFORE: ['beau', 'intelligent'], AFTER: ['brun'] } })]` will generate _une belle et intelligente vache brune_.

Use `SEP_BEFORE` and `SEP_AFTER` to override the default separator between adjectives (defaut is localized _and_): for instance, in Spanish, `\#[+value('árbol', { det:'DEFINITE', adj:{BEFORE:['primero', 'grande'], SEP_BEFORE:''} })]` will output _el primer gran árbol_.

WARNING: In `agreeAdj` and `subjectVerbAdj` mixins, you can also put a list of adjectives, but there is a difference: `value` will output all the adjectives, while `agreeAdj` and `subjectVerbAdj` will randomly choose one.


=== Possessive adjectives (Italian only)

In Italian, you can add a possessive adjective: `\#[+value('gioiello', {det: 'DEFINITE', possessiveAdj:'mio'})]`. 
You could also use `adj` directly but possessive adjectives are automatically placed properly.


=== Examples

++++
<script>
spawnEditor('fr_FR', 
`p
  | #[+value('homme', {det:'INDEFINITE', adj:'vieux', adjPos:'BEFORE'})] /
  | #[+value('Hollandais', {det:'INDEFINITE', adj:'vieux', adjPos:'BEFORE'})] /
  | #[+value('vache', {det:'INDEFINITE', adj:{ BEFORE: ['beau', 'intelligent'], AFTER: ['brun'] } })]
`, 'n vieil homme / un vieux Hollandais / une belle et intelligente vache brune'
);
</script>
++++

++++
<script>
spawnEditor('it_IT', 
`p
  | #[+value('specchio', {adj:'bello', adjPos:'AFTER', number:'P'})] /
  | #[+value('specchio', {adj:'bello', adjPos:'BEFORE', number:'P'})] /
  | #[+value('gioiello', {det: 'DEFINITE', possessiveAdj:'mio'})]
`, 'pecchi belli / begli specchi / il mio gioiello'
);
</script>
++++


== Case (German only)

In German, use `case` to indicate the case: `NOMINATIVE`, `ACCUSATIVE`, `DATIVE` or `GENITIVE`.

`\#[+value('Gurke', {case:'GENITIVE', det:'DEFINITE', adj:'alt'})]` will output _der alten Gurke_.


== Assign the gender of the word to an object

This is useful when using xref:referring_expression.adoc[referring expressions]: different words, having potentially a different gender (and sometimes number) can be used to refer to a same concept (in practice an object).

Use `represents` to assign the gender of the word to the representant.

TIP: only useful for languages with a gender, like French, German, Italian, Spanish etc. - not for English.

.All those 4 constructions do exactly the same thing
[cols="2"]
|===
a|
Just plain text, and setting gender directly:
....
\| cette bague
- setRefGender(PRODUIT, 'F');
....

a|
Just plain text, and using the dictionnary to set the gender (French or German):
....
\| cette bague
- setRefGender(PRODUIT, 'bague');
....

a|
Using value with `represents` option (and dictionnary lookup):
....
\| cette #[+value('bague', {represents: PRODUIT})]
....

a|
Using value with `represents` and `det` options (and dictionnary lookup):
....
\| #[+value('bague', {represents: PRODUIT, det: 'DEMONSTRATIVE'})]
....

a|
Using xref:value_simplified_syntax.adoc[Simplified Syntax]:
....
\| #[+value('<ce bague>', {represents: PRODUIT})]
....
|===


== Number and gender

=== Number

The determiner, noun and adjectives can be agreed in number. You can set explicitely the number using `number`:

* can be directly `S` or `P`: `\#[+value('affaire', {det:'INDEFINITE', number:'P'})]` will output _des affaires_
* or you can refer to an existing object that carries a number: `\#[+value("tomato", { number: getAnonMP() } )]` will output _tomatoes_

++++
<script>
spawnEditor('en_US', 
`-
  var DIAMONDS = {bla: 'bla'};
  setRefNumber(DIAMONDS, 'P');

p #[+value("diamond", {number:DIAMONDS})]
`, 'iamonds'
);
</script>
++++

TIP: If the gender of the word cannot be determined automatically from the dictionnary (for instance it is a brand name), you can add a `gender` key.

TIP: It indicates the number of the _owned_ object. When using possessives, you might also have to indicate the _owner_ of the object.


=== Gender

By default the gender is automatically inferred from the word itself, using linguistic resources. 

When some words or expressions are not in the dictionnary, you must indicate explicitely the gender. For instance, `\#[+value('OnePlus 5T', {represents: PRODUKT2, gender:'N', det: 'DEFINITE'})]` will output _das OnePlus 5T_ in German, and also assign `N` to current gender of `PRODUKT2`.


== Ownership

Use `owner` to indicate an owner. See xref:possessives.adoc#thirdPossession[third possession].


== List of nouns

First parameter is generally a single noun, but you can also put a list. One noun will randomly be chosen.

++++
<script>
spawnEditor('fr_FR', 
`p
  - const OBJ = {bla:'bla'};
  l
    eachz elt in [1,2,3,4,5,6,7,8,9,10] with { separator: ',', last_separator: ',' }
      | #[+value(['alsacien', 'homme', 'maison', 'gourou'], {det:'DEFINITE', adj:'vieux', adjPos:'BEFORE', represents: OBJ})]
      | est
      | #[+agreeAdj('vieux', OBJ)]
`, 'est vi'
);
</script>
++++
