// Copyright 2019 Ludan Stoecklé
// SPDX-License-Identifier: CC-BY-4.0
= Value mixin

The `value(obj, params)` mixin is the entry point to insert a value in a text. Its behavior depends of the type of `obj`.

TIP: `value` is the entry point of many RosaeNLG powerful features. Don't miss it!

== Number

When `obj` is a *number*, you can indicate how to format it: units, ordinals, cardinals, etc. 
For instance, `&#35;[+value(5500, {'TEXTUAL':true })]` will output _five thousand five hundred_.

See xref:value_numbers.adoc[Value for Numbers].

== Date

When `obj` is a *date*, the `date-fns` lib will be used to format it. You should put a parameter to indicate how to format it. See xref:value_dates.adoc[Value for Dates].


== String / noun

When `obj` is a *string*, it will either just output the string, or generate a nominal group if more parameters are set.
For instance, `&#35;[+value('apple', { det:'INDEFINITE', adj:'big' })]` will generate _a big apple_.

See xref:value_nominal_groups.adoc[Value for Nominal Groups].

There is an alternative xref:value_simplified_syntax.adoc[Simplified Syntax] available for some languages.


== Structured object

When `obj` is a *structured object*, it will trigger the referring expressions mechanisms.

The first parameter is an object, and there are generally very few additional parameters: for instance, `&#35;[+value(PRODUCT)]` or `&#35;[+value(PRODUCT, {REPRESENTANT: 'ref'})]`.

You have to define how to transform the structured object into text.

See xref:referring_expression.adoc[referring expressions].

When integrating rosae with typescript, you can also use the additional parameter `deprel` to pass information about the grammatical function of the object to the referring expressions mixins: for instance, you can restrict the use of the pronoun `he` or `she` to the subject of a sentence.

== Value of a mixin

When the first parameter is a mixin, this mixin will be called, and the additional parameters of value will simply be sent to the mixin.

++++
<script>
spawnEditor('en_US', 
`
mixin mixinToCall(param)
  | some text with
  +value(param)

| #[+value(mixinToCall, 5)]
`, 'Some text with 5'
);
</script>
++++

