// Copyright 2019 Ludan Stoecklé
// SPDX-License-Identifier: CC-BY-4.0
= French Verbs Support

Any verb of all 3 verb groups are available thanks to `lefff` derived resource: `ils &#35;[+verb(subjMP, 'oindre')]` will output _ils oignent_.

Supported tenses are:

* `PRESENT`
* `FUTUR`
* `IMPARFAIT`
* `PASSE_SIMPLE`
* `PASSE_COMPOSE`
* `PLUS_QUE_PARFAIT`
* `PASSE_ANTERIEUR`
* `FUTUR_ANTERIEUR`
* `CONDITIONNEL_PRESENT`
* `CONDITIONNEL_PASSE_1`
* `CONDITIONNEL_PASSE_2`
* `IMPERATIF_PRESENT`
* `IMPERATIF_PASSE`
* `SUBJONCTIF_PRESENT`
* `SUBJONCTIF_IMPARFAIT`
* `SUBJONCTIF_PASSE`
* `SUBJONCTIF_PLUS_QUE_PARFAIT`
* `INFINITIF`
* `INFINITIF_PASSE`
* `PARTICIPE_PRESENT`
* `PARTICIPE_PASSE`
* `PARTICIPE_PASSE_COMPOSE`

For composed tense, you have to indicate:

. Which auxiliary to use (_être_ or _avoir_): set `aux` to `AVOIR` or `ETRE`
. With what to agree the participle (optional, masculine singular being the default): set `agree`
. NB: when `aux` is `ETRE`, the participle is automatically agreed with the subject

For instance:

* `elles &#35;[+verb(getAnonFP(), {verb: 'sortir', tense:'PASSE_COMPOSE', aux:'ETRE', agree: getAnonFP()})]` will generate _elles sont sorties_
* `elles &#35;[+verb(getAnonFP(), {verb: 'sortir', tense:'PASSE_COMPOSE', aux:'AVOIR'})] la poubelle` will generate _elles ont sorti la poubelle_


If the auxiliary is not set, these rules will apply:

* pronominal verbs always use `ETRE`
* there is a short list of verbs that always take `ETRE`
* transitive verbs rather take `AVOIR`


TIP: `PASSE_COMPOSE` can be used to mimic the passive form. `elle &#35;[+verb(getAnonFS(), {verb: 'convoquer', tense:'PASSE_COMPOSE', aux:'ETRE', agree:getAnonFS()})]` will output _elle est convoquée_. But `elle &#35;[+subjectVerbAdj(getAnonFS(), 'être', 'convoqué')]` generates the same output and is much simplier.

You can also use the parameter `voice: 'Pass'`

Pronominal form using `pronominal:true`: `ils &#35;[+verb(getAnonMP(), {verb: 'immerger', tense:'IMPARFAIT', pronominal:true})]` will output _ils s'immergeaient_.

++++
<script>
spawnEditor('fr_FR', 
`p
  | ils #[+verb(getAnonMP(), 'chanter')] /
  | ils #[+verb(getAnonMP(), {verb: 'faire', tense: 'PASSE_SIMPLE'})] /
  | il #[+verb(getAnonMS(), {verb: 'aller', tense:'PASSE_COMPOSE', aux:'ETRE'})] /
  | ces fleurs, il les #[+verb(getAnonMS(), {verb: 'couper', tense:'PASSE_COMPOSE', aux:'AVOIR', agree:getAnonFP()})] /
  | elles #[+verb(getAnonFP(), {verb: 'arrêter', tense:'PASSE_COMPOSE', aux:'ETRE', agree:getAnonFP(), pronominal:true})]
`, 'il les a coupées'
);
</script>
++++
