= Developer documentation

Read this if you want to contribute to FreeNLG.
Alternatively, this is my own personal doc when I forget how things work.

== The repo

It is a multi package repo which is a fork of Pug @2.0.3 (as of 06/04/2018).

* `freenlg` is `pug` renamed. I try to do as little changes as possible.
* `freenlg-core` is the main package. It contains all FreeNLG's logic.
* `freenlg-pug-xxx` are forks of the original `pug-xxx` packages:
** Some of them are are unchanged, but I needed to fork them because they carry dependancies with changed packages: `freenlg-pug-filters` `freenlg-pug-linker` `freenlg-pug-load`
** Some of them are changed to handle specific structures like `synz > syn`: `freenlg-pug-lexer` `freenlg-pug-parser` `freenlg-pug-walk` `pug-code-gen`

== Install

Linking: `lerna bootstrap`

Build the linguistic resources: `lerna run build`

Run the tests: `lerna run test`


== Linking a FreeNLG project with the local copy of the repo

In your project: *do not* run `npm install` as it will download each FreeNLG package. And do not use `npm link`.

* just install the other dependancies: for instance `npm install junit`
* make a symbolic link in your project to your local copy of FreeNLG: `mklink /D node_modules\freenlg c:\freenlg\freenlg-lerna\packages\freenlg`


== Publishing a new version

_this doc is just for me_

* local environement: `lerna publish --skip-npm --cd-version patch --yes`
* merge with master
* push with tags: `git push --follow-tags`
* Travis should to the rest of the publishing tasks

