== Listing things with `foreach` and `assemble`

You don't really need FreeNLG to do loops: pug has `each` and `while` methods. But when doing NLG you often want to generate texts like _A, B, C and D_: there's one general kind of separator, the comma, and another one between the two last elements, the "and".
When you have only two elements you would like to generate _A and B_, not _A, B_.
This is why you need a proper way to list elements.

* When the elements to list are in a javascript array, use <<foreach>>. For instance you want to list products.
* When the elements to list are texts, mixins etc., use <<assemble>>. For instance when you want to list the characteristics of a product, each characteristics of the product will have its own mixin.
* The ways to assemble the elements are the same for `foreach` and `assemble`: see <<assembly_parameters>>.


anchor:foreach[foreach mixin]

=== The `foreach` mixin

==== First example

....
-
  var elts = ['A','B','C','D']

mixin showElt(elt)
  | #{elt}

p #[+foreach(elts, 'showElt', { separator: ', ', last_separator: ' and ' })]
....
This will output _A, B, C and D_.

Parameters:

. An array of elements to iterate on
. The name of a mixin. This mixin has to take an element of the array as its first parameter. You can do whatever you want in this mixin.
. An assembly structure. See <<assembly_parameters>>


==== Empty elements

It will only output non-empty elements. For instance:
....
-
  var elts = ['A','B','C','D']

mixin showEltNOT_BC(elt)
  if ['B','C'].indexOf(elt)==-1
    | #{elt}

p #[+foreach(elts, 'showEltNOT_BC', { separator: ', ', last_separator: ' and ' })]
....
This will output _A and D_ (and not _A, D_).

==== Parameters for the mixin

The first parameter of your mixin must an element of the array. But you can send more parameters:
....
mixin showEltNOT_B_flag(elt, params)
  if elt!='B' || !hasFlag(params, 'NOT_B')
    | #{elt}

p #[+foreach(elts, 'showEltNOT_B_flag', { separator: ', ', last_separator: ' and ' }, {NOT_B:true})]
....
Output will be _A, C and D_.


anchor:assemble[assemble mixin]

=== The `assemble` mixin

Use it to list text elements that are output by another mixin.
....
- setSize('materials_list', 3)
mixin materials_list(pos)
  case pos
    when 1
      | the ring has a huge central diamond
    when 2
      if PRODUCT.gold
        | it is made with gold
    when 3
      | it has 3 other diamonds

p #[+assemble('materials_list', {separator: ', ', last_separator: ' and '})]
....
This will output _The ring has a huge central diamond, it is made with gold and it has 3 others diamonds_ if `PRODUCT.gold` is true.
As usual, empty elements will be ignored (here when `PRODUCT.gold` is false).


You can also send parameters to your mixin:
....
- setSize('materials_list', 3)
mixin materials_list(pos, params)
  ...
p #[+assemble('materials_list', {separator: ', ', last_separator: ' and '}, {some parameters})]
....


anchor:assembly_parameters[Assembly parameters]

=== Assembly parameters

WARNING: There are plenty of parameters combinations and they have not all been tested.

You can generate either:

* a single sentence: this is the default, you can also put `mode: 'single_sentence'`
* multiple sentences:
** sentences with a new HTML paragraph: `<p>...</p>`: put `mode: 'paragraphs'`
** without: put `mode: 'sentences'`

==== Common parameters

* `shuffle`: boolean. the elements of the list are shuffled before being listed. This is often used to add diversity to the texts.
* `separator`: default separator between to elements. Often "," when mode is single sentence, often "." otherwise.
* `begin_with_general`: what the sentence should begin with. Could be _The products are:_. Often combined with `begin_with_1` and `if_empty`
* `begin_with_1`: what the sentence should begin with when there is only one element. Could be _The only products is:_
* `if_empty`: what the sentence should begin with when there it is empty. Defaults to nothing. Could be _No products today_.
* `end`: what the sentence should end with when it is not empty.

==== Single sentence specific parameters

* `last_separator`: the last separator. Often " and ".

.Single sentence example
....
#[+foreach(elts, null, { separator: ', ', last_separator: ' and ' })]
....
will output _A, B, C and D_.


==== Multiple sentences specific parameters

* `begin_with_general` can be an array. Each element of the array will be output at the beginning of each new sentence, until exhaustion.
* `begin_last` : last beginning of sentence. Could be _at last_.
* `begin_last_1`: the previous to last beginning. Could be _finally_.

.Multiple sentences example
....
#[+foreach(['A','B','C','D','E'], null, {mode:'sentences', separator: '.', begin_with_general: ['first,','second,'], begin_last_1: 'as well,', begin_last: 'at last,'})]
....
will output _First, A. Second, B. C. As well, D. At last, E._.

TIP: Classic parameters can be either string or mixins. Using a mixin is convenient when the content is variable, often for `begin_with_1`. These mixins can even receive parameters:

....
mixin mixinLastSep(params)
  if hasFlag(params, 'LAST_SEP_IS_ALT')
    | ALT_LAST_SEP
  else
    | LAST_SEP

p #[+assemble(..., {last_separator: 'mixinLastSep'}, {LAST_SEP_IS_ALT: true})]
....
