== Style and tricks

=== Missing space

Sometimes it looks like Pug forgets to add a space where it should, especially when using conditions. You end up with concatenated words. This is a known topic.
See https://pugjs.org/language/plain-text.html: Whitespace Control section.
You should use an empty piped line (a pipe with either spaces or nothing after it) to force a space in the output.

=== Horizontal ellipsis (`…` and `...`)

Three dots (`...`) are automatically transformed into `…`. You can also put `…` directly in your mixins.

Capitalization is not automatic after `…` because it is not systematic:
[quote, Chicago Manual of Style 13.51]
____________________________________________________________________
The first word after an ellipsis is capitalized if it begins a new grammatical sentence.
____________________________________________________________________

=== When assembling, knowing which eleements are empty

When you list elements, it is sometimes (but very rarely) useful to be able to know which elements are empty and which are not. 

The list of the non empty elements is made available in `params.nonEmpty`:
....
...
| #[+assemble(..., {..., begin_last:'linkWord'})] 
...
mixin linkWord(params)
  //- if 4th element is not present, we trigger the link word
  if params.nonEmpty.indexOf(4)>-1
    | finally,
....

* When in a `foreach`, elements are objects, while when in an `assemble`, elements are integers.
* When you read `params.nonEmpty`, it can be `undefined`: this happens when FreeNLG tests if the elements are empty or not. FreeNLG will actually make a second call with `params.nonEmpty` properly populated. Thus just test and ignore if `undefined`.

