# Copyright 2019 Ludan Stoecklé
# SPDX-License-Identifier: Apache-2.0
name: simple workflow

snippets:
  shortvariables: &shortvariables
    -
      name: inject slug/short variables
      uses: rlespinasse/github-slug-action@v2.x
  nodeversion: &nodeversion
    - 
      name: use proper version of node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
  cachenode: &cachenode
    - 
      name: cache node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-


on:
  push:
    branches:
      - '*'
      - '!v*.*.*'

jobs:

  build_test:
    name: Build, test and save build artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      <<: *shortvariables
    -
      <<: *nodeversion
    -
      <<: *cachenode
    - 
      name: check environment versions
      run: |
        npm -v
        node --version
    - name: install environment
      run: |
        npm install -g pegjs
        npm install -g lerna
        yarn install
        rm -f packages/rosaenlg/dist/rollup/*.js
    - name: build
      run: |
        lerna run build
    - name: test
      run: |
        lerna run test
    - name: save build
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ env.GITHUB_REF_SLUG }}
        path: |
          packages/*/resources_pub
          packages/*/dist
          packages/*/coverage
          packages/*/lib
          packages/*/.serverless
        retention-days: 1

  sonarcloud:
    name: SonarCloud
    needs: [build_test]
    runs-on: ubuntu-latest
    steps:
    -
      <<: *shortvariables
    - uses: actions/checkout@v2
    - 
      name: download build
      uses: actions/download-artifact@v2
      with:
        name: build-${{ env.GITHUB_REF_SLUG }}
        path: ./packages
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
