# Copyright 2019 Ludan Stoecklé
# SPDX-License-Identifier: Apache-2.0
name: simple workflow

snippets:

on:
  push:
    branches:
      - '*'
      - '!v*.*.*'

jobs:

  build_test:
    name: Build, test and save build artifacts
    runs-on: ubuntu-latest
    steps:
    -
      <<: *checkout_deep
    - 
      name: some debug
      run: |
        # git branch -a
        BRANCH="$(git branch --show-current | sed 's/\n//')"
        echo "branch: --${BRANCH}--"

        BRANCH2="$(git branch --show-current)"
        echo "branch2: --${BRANCH2}--"

    -
      <<: *shortvariables
    -
      <<: *nodeversion
    -
      <<: *cachenode
    -
      <<: *cacheperfmon
    -
      <<: *checkenv
    -
      <<: *installenv
    -
      <<: *build
    -
      <<: *test
    -
      <<: *zipbuild
    -
      <<: *savebuild

  sonarcloud:
    name: SonarCloud
    needs: [build_test]
    runs-on: ubuntu-latest
    steps:
    -
      <<: *shortvariables
    -
      <<: *checkout
    -
      <<: *downloadbuild
    -
      <<: *unzipbuild
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
