# Copyright 2019 Ludan Stoecklé
# SPDX-License-Identifier: Apache-2.0
name: simple workflow

snippets:

on:
  push:
    branches:
      - '*'
      - '!v*.*.*'

jobs:

  build_test:
    name: Build, test and save build artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      <<: *shortvariables
    -
      <<: *nodeversion
    -
      <<: *cachenode
    -
      <<: *cacheperfmon
    - 
      name: check environment versions
      run: |
        npm -v
        node --version
    - name: install environment
      run: |
        npm install -g pegjs
        npm install -g lerna
        yarn install
        rm -f packages/rosaenlg/dist/rollup/*.js
    - name: build
      run: |
        lerna run build
    - name: test
      run: |
        lerna run test
    -
      <<: *savebuild

  sonarcloud:
    name: SonarCloud
    needs: [build_test]
    runs-on: ubuntu-latest
    steps:
    -
      <<: *shortvariables
    - uses: actions/checkout@v2
    - 
      name: download build
      uses: actions/download-artifact@v2
      with:
        name: build-${{ env.GITHUB_REF_SLUG }}
        path: ./packages
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
