anchor:synonyms[Synonyms]

== Synonyms

You can output simple synonyms (words etc.) with `syn` and complex ones (which use mixins or other synonyms etc.) using `synz > syn` structure.

The algorithm that chooses the synonym to output works like that:

* It is random based (nothing fancy but efficient), or sequence based (one after the other), depending on the mode
* It eliminates empty alternatives.

You should *not use your own random numbers in your mixins*, because it will break FreeNLG's ability to predict the next outputs. More about FreeNLG and random numbers here: <<random_numbers>>.

=== Basic synonyms using `syn`

The `syn` mixin is perfect for very basic synonyms.
....
The diamond is #[+syn('shiny','gleaming','glossy')] .
....
Arguments can be single words, multiple words or anything, but not mixins.
Please note that the argument is not an array: the mixin takes a variable number of arguments.

With this mixin the choice is always random. Use `syno_sentences` if you want more options like sequential output.

=== The `syn_fct` function

The "syn_fct" is not a mixin but a standard javascript function. Its argument is an array
It is useful when you want random arguments in some other mixins. Remind, do not use you own random function.

....
#[+subjectVerbAdj(THE_PERSON, {verb: syn_fct(['eat','ingest','swallow'])}) some bread.
....


=== Complex synonyms with `synz > syn` structure

==== First example

When each synonymic alternative is complex text using mixins, `syn` doesn't fit. You have to use the `synz > syn` structure.

....
synz
  syn
    | first alternative
  syn
    | second alternative
  syn
    | third alternative
....

You can put sentences or words or whatever you want in each `syn`.

==== Note on empty alternatives

FreeNLG will always try to find a non-empty alternative in a `synz > syn` structure. When it triggers an empty one, it will go back and try to find a new one.

==== Weights of each alternative

If you want to favor an alternative more than the other, you can just repeat the one you prefer:
....
synz
  syn
    | first alternative
  syn
    | the one I prefer
  syn
    | the one I prefer
  syn
    | the one I prefer
....
The _the one I prefer_ option will be triggered much more often.

anchor:synonyms_sequence[Synonyms in sequence]

==== Choose each synonym alternative one after the other

Sometimes random is not the right way. You might prefer to trigger the first alternative, then the second one, etc. Use the `sequence` parameter to do that.

....
synz 'sequence'
  syn
    | first
  syn
    | second
  syn
    | third
  syn
    | fourth
....
When called 5 times, will output: _first second third fourth first_

anchor:synonyms_mode[Synonyms global mode]

==== Global synonym mode

By default, the synonyms are choosen randomly, and you can locally change this behavior using `sequence` param. But you can change the behavior globally using `defaultSynoType`.

When you have changed `defaultSynoType` to `sequence`, you can still change the default behavior locally using `random` (instance of the `sequence` keyword).

