anchor:value[Value]

== Value mixin

The `value(obj, params)` mixin is the entry point to insert a value in a text. Its behavior depends of the type of `obj`.


=== Structured object

When it is a *structured object*, you have to define how to transform it into text: see <<referring_expression>>.

=== String

When it is a *string*, it will be output as is. You can protect it from untimely capitalization etc. using `protectString`.

Additional parameters:

* `represents` to assign the gender of the word to the representant (in French).
* `det` to add a determinant (French and English); current determinants are `DEFINITE` and `DEMONSTRATIVE`.

.All those 4 constructions do exactly the same thing:
[cols="2"]
|===
a|
Just plain text, and setting gender directly:
....
| cette bague
- setRefGender(PRODUIT, 'F');
....

a|
Just plain text, and using the dictionnary to set the gender:
....
| cette bague
- setRefGender(PRODUIT, 'bague');
....

a|
Using value with `represents` option:
....
| cette #[+value('bague', {represents: PRODUIT})]
....

a|
Using value with `represents` and `det` options:
....
| #[+value('bague', {represents: PRODUIT, det: 'DEMONSTRATIVE'})]
....
|===


[cols="2"]
|===

a|This cell is prefixed with an `a`, so the processor interpets the following lines as an AsciiDoc list.

* List item 1
* List item 2
* List item 3
|
a|This cell *is not* prefixed with an `a`, so the processor does not interpret the following lines as an AsciiDoc list.

* List item 1
* List item 2
* List item 3

a|This cell is prefixed with an `a`, so the processor honors the `lead` style on the following paragraph.

[.lead]
I am a paragraph styled with the lead attribute.
|
a|This cell *is not* prefixed with an `a`, so the processor does not honor the `lead` style on the following paragraph.

[.lead]
I am a paragraph styled with the lead attribute.
|===


[cols="2"]
|===

a|
[source,python]
----
import os
print "%s" %(os.uname())
----

a|
[source,python]
----
import os
print ("%s" %(os.uname()))
----

a|
[source,python]
----
import os
print "%s" %(os.uname())
----

a|
Using value with `represents` and `det` options:
----
| #[+value('bague', {represents: PRODUIT, det: 'DEMONSTRATIVE'})]
----
|===



=== Date

When it is a *date*, the `moment` lib will be used to format it. You should put a parameter to indicate how to format it: `#[+value( new Date('1980-04-14') , 'LL')]` will output _April 14, 1980_ in English.

See http://momentjs.com/docs/#/displaying/[displaying dates with moment.js] for options.

TIP: The date has to be a real standard javascript date, not a string. If you have a string parse it before, using `new Date(string)` or `util.moment`.

=== Number

When it is a *number*, you have various options:

* by default it will format the number accordingly to the locale: `562407` will output _562,407_ in `en_US`, _562 407_ in `fr_FR` (thanks to `format-number-french` lib)
* set `AS_IS` flag to `true` to avoid this (available in any language)
* set `TEXTUAL` flag to `true` to transform the number into text: `#[+value(5500, {'TEXTUAL':true })]` will output _five thousand five hundred_
* set `ORDINAL_NUMBER` flag to true to to transform the number into an ordinal number: `#[+value(21, {'ORDINAL_NUMBER':true })]` will output _21st_
* set `ORDINAL_TEXTUAL` flag to true to to transform the number into an ordinal text: `#[+value(21, {'ORDINAL_TEXTUAL':true })]` will output _twentieth_
* use `FORMAT` to set a format directly used by `numeral`. See http://numeraljs.com/#format[numeral.js formats]. Very practical for currencies, %, etc.

INFO: `numeral` takes into account the locale: `+value(104000, {'FORMAT': '0a$'})` will output _104k€_ (yes, €!) when generating French.

.Number formatting support depending on languages
[options="header"]
|=====================================================================
| Feature  | en_US  | fr_FR | de_DE
| Default: standard number formating | yes | yes | yes
| `TEXTUAL` | yes | yes (but doesn't work with decimal numbers) | yes (doesn't work with decimal numbers)
| `ORDINAL_NUMBER` | yes | yes | yes
| `ORDINAL_TEXTUAL` | yes | yes (up to 100) | yes (up to 100)
| `FORMAT` | yes | yes | yes
|=====================================================================
