= Developer documentation

Read this if you want to contribute to FreeNLG.
Alternatively, as the author, this is my own personal doc when I forget how things work.

== The repo

On Gitlab:

* Project group: https://gitlab.com/freenlg-projects
* Main project: https://gitlab.com/freenlg-projects/freenlg

It is a multi package repo (lerna) which is a fork of Pug @2.0.3 (as of 06/04/2018).

* `freenlg` is the main package. Derived from `pug`.
* `freenlg-pug-xxx` are forks of the original `pug-xxx` packages:
** Some of them are are unchanged, but I needed to fork them because they carry dependancies with changed packages: `freenlg-pug-filters` `freenlg-pug-linker` `freenlg-pug-load`
** Some of them are changed to handle specific structures like `synz > syn`: `freenlg-pug-lexer` `freenlg-pug-parser` `freenlg-pug-walk` `pug-code-gen`
* `freenlg-yseop` is an Yseop template generator for FreeNLG templates, derived from `freenlg-pug-code-gen` (itself a fork of `pug-code-gen`).
* and multiple packages that each contain a set of features


== Pre instal

* lerna: `npm install -global lerna`
* yarn: `npm install -global yarn`
* mocha: `npm install --global mocha`

== Install

* Linking: `lerna bootstrap`.
* Build the linguistic resources and the typescript files: `lerna run build`.
* Run the tests: 
** `lerna run test`
** I also use `npm test` directly in `packages/freenlg` folder
** and also `mocha test-freenlg/unit.js _lang_fr_FR` etc. to run a specific test

== Linking a FreeNLG project with the local copy of the repo

In your project: *do not* run `npm install` as it will download each FreeNLG package. And do not use `npm link`.

* just install the other dependancies: for instance `npm install junit`
* make a symbolic link in your project to your local copy of FreeNLG: `mklink /D node_modules\freenlg c:\freenlg\freenlg\packages\freenlg`


== Publishing a new version

_this doc is just for me_

* merge with master
* local environement: `lerna version --no-push --exact patch` (or `minor` etc. instead of patch)
* push with tags: `git push --follow-tags`
* Gitlab CI should to the rest of the publishing tasks

Packages are on npm: https://www.npmjs.com/settings/freenlg/packages
