= Developer documentation, Contribute

Read this if you want to contribute to RosaeNLG.

Check:

* xref:build_test.adoc[Build and test RosaeNLG] from its source code
* xref:add_language.adoc[Add a new language] to RosaeNLG


== Code

Code is on Github:

* link:https://github.com/RosaeNLG[RosaeNLG project group]
* link:https://github.com/RosaeNLG/rosaenlg[Main project]

link:https://sonarcloud.io/dashboard?id=RosaeNLG_RosaeNLG[Sonar dashboard]

== Project Structure

Multi package repo (lerna) which is a fork of Pug @2.0.3 (forked 2018-04-06). Pug @3.0.0 was published 2020-05-25.

* `rosaenlg` is the main package. Derived from `pug`.
* `rosaenlg-pug-xxx` are forks of the original `pug-xxx` packages:
** Some of them are are unchanged, but I needed to fork them because they carry dependencies with changed packages: `rosaenlg-pug-filters` `rosaenlg-pug-linker` `rosaenlg-pug-load`
** Some of them are changed to handle specific structures like `synz > syn`: `rosaenlg-pug-lexer` `rosaenlg-pug-parser` `rosaenlg-pug-walk` `pug-code-gen`
* `rosaenlg-yseop` is an Yseop template generator for RosaeNLG templates, derived from `rosaenlg-pug-code-gen` (itself a fork of `pug-code-gen`).
* and multiple packages that each contain a set of features
