anchor:inbrowser[client side in browser rendering]

= Client side in browser compiling and/or rendering

The idea is to do NLG in the browser. You can:

* compile the templates server side and just render (generate texts) in the browser, which is the most common usage
* both compile and render client side in the browser


== Client side in browser rendering

The idea is to generate texts client side, _in a browser_, _without node.js_.

A use case is for business intelligence application, where charts are generated on the fly dynamically in the browser, and with FreeNLG one could do the same for texts.

=== Limits

Generating texts in the browser works perfectly. There are 2 limitations to be aware of:

* The default bundled packages per language do not contain most of their linguistic resources to make them lighter. The linguistic resources have to be bundled inside it at compile time: the ones which are effectively used in templates are collected automatically during compilation, and you can also indicate expressly the other ones.
* The simplified syntax (`<...>`, see <<simplified>>) is desactivated for `fr_FR` and `de_DE`: you cannot use it in your templates when doing client side rendering in those languages. The reason is that this feature requires `lefff-helper` module (for French) and `german-dict-helper` (for German), and that they both have a dependancy on `sqlite`, which cannot run in a browser.


=== How to make it work

A possible pipeline is the following:

* compile your templates using `compileFileClient` (put `embedResources` to true)
* package them using `browserify`
* import the compiled template and the proper `freenlg_*_*.js` lib in your webpage
* generate texts in your webpage just calling the template

TIP: You can use `gulp-freenlg` to ease the two first steps.

In your html file, import the proper packages. `compiled_en_US.js` is the compiled and packaged template.
[source,html]
....
<script src="compiled_en_US.js"></script>
<script src="freenlg_en_US.js"></script>
....

In your html file, run this javascript to generate texts:
[source,javascript]
....
let rendered = templates_holder.template_name({
  util: new freenlg_en_US.NlgLib({language: 'en_US'}),
  data: ...
});
....
`templates_holder` is the name of the package containing the compiled template; it an option when calling `browserify`, and also an option of `gulp-freenlg`.

TIP: For a complete technical POC that effectively generates texts in a browser using FreeNLG, see separate repo `freenlg-browser-poc`.


=== Bundling linguistic resources

Linguistic resources (extensive lists of verbs, words, adjectives) are not bundled directly inside the packaged versions for browsers: if they were, the packages would be too large to be transfered to a browser. Moreover, a project typically only uses effectively a few verbs/words/adjectives among the whole available list.

To bundle linguistic resources:

* When *compiling*, you *must* provide the `language` parameter. While you generally don't have to indicate language at compile time, here it is necessary so that FreeNLG knows how to resolve resources to bundle them.
* When *compiling*, you *must* set `embedResources` to true so that FreeNLG knows it must embed resources in the compiled template.
* Some/most of the verbs/words/adjectives are properly detected at compile time and properly embedded automatically. For instance in `#[+verb(..., {'verb' : 'danser', tense:'FUTUR'} )]`, _danser_ will be detected.
* For the verbs/words/adjectives which are not properly detected (for instance in `#[+verb(..., getVerbXXX() )]` - and you will see it at runtime when rendering fails), you can explicitly indicate the resources to embed. Use `verbs`, `words`, `adjectives` parameters in the compile options; all of them are lists

.Linguistic resources which can be bundled per language
[options="header"]
|=======================================
| Language | Linguistic resources
| `en_US` | NA
| `fr_FR` | verbs, words
| `de_DE` | verbs, words, adjectives
|=======================================

A complete example in French:
[source,javascript]
....
const templateVerb = `
p
  | il #[+verb(getAnonMS(), {verb: 'chanter', tense:'FUTUR'} )]
`;

const compiled = freenlgPug.compileClient(templateVerb, {
  language: 'fr_FR',
  compileDebug: false,
  embedResources: true
});

const compiledFct = new Function('params', `${compiled}; return template(params);`);

let rendered = compiledFct({
  util: new NlgLib({language: 'fr_FR'})
});
....
will output _il chante_, without requiring any linguistic resource at runtime.

TIP: When a resource has been forgotten, execution will fail; watch for logs as they should indicate the exact name of the forgotten resource (e.g. `could not read xxxx on disk: ...`).

TIP: Auxiliary verbs (_être_ and _avoir_ for French, _sein_, _haben_ and _werden_ for German) are always automatically included.


== Client side in browser compiling and rendering

Both compilation and rendering are made in the browser: templates can be authored directly in the browser, or dynamically generated, compiled in the browser and the texts can also be rendered in the browser.

To be able to do that, you must use a js version of freeNLG that is larger, with `_comp` at the end, like `freenlg_tiny_fr_FR_0.15.6_comp.js`:

* it includes the templates compiler
* but also all linguistic resources that are associated with a language

TIP: Client side compilation is for exotic usecases. You should favor server side compilation.

It can be used to create a 100% client side editor and renderer, like in this demo: http://freenlg.org/demo/demo.html[in browser editor].

TIP: For a complete technical POC that effectively generates texts in a browser using FreeNLG, see separate repo `freenlg-browser-poc`.

== Packaged version of FreeNLG for client side usage

FreeNLG provides browser ready "tinyified" packages per language in `dist/browser`:

.Available packages per language
[options="header"]
|=====================================================================
| File name | Compilation  | Rendering | Language | Size (approx.)
| `freenlg_en_US.js`      | no  | yes | `en_US` | 773 Kb
| `freenlg_fr_FR.js`      | no  | yes | `fr_FR` | 582 Kb
| `freenlg_de_DE.js`      | no  | yes | `de_DE` | 541 Kb
| `freenlg_en_US_comp.js` | yes | yes | `en_US` | 1 681 Kb
| `freenlg_fr_FR_comp.js` | yes | yes | `fr_FR` | 8 615 Kb
| `freenlg_de_DE_comp.js` | yes | yes | `de_DE` | 33 533 Kb
|=====================================================================

