// Copyright 2021 Ludan Stoecklé
// SPDX-License-Identifier: CC-BY-4.0
= Changelog

////
https://keepachangelog.com/en/0.3.0/

== [Unreleased]

=== Added

=== Fixed

=== Changed

////

== [Unreleased]

=== Added

=== Fixed

* &#35;152: Hn tags (`<h1>`, `<h2>` etc.) are now considered as structure tags (like `<p>`), thus having capitalization
* &#35;150: when we had a span around a word, the space after that word were eaten (thanks blegaut)

=== Changed

* &#35;148: on bulleted lists, use `list_last_end_item` to have a specific ending for the last item in the list

== [3.2.5] - 2022-08-02

=== Added

* &#35;100: adds official names of the countries, instead of just common names, e.g. _French Republic_ while _France_ is the common name

=== Fixed

* &#35;131: suppressed wrong dependencies of `english-verb-helper`
* dependency updates to solve some security issues


== [3.2.4] - 2022-07-08

=== Added

* &#35;127: in French, "de des" contracts in "de"
* &#35;128: (most) raw numbers are automatically protected from filtering


== [3.2.3] - 2022-06-18

=== Added

* added `zh_CN` language, with only one feature: no extra spaces added when enumerating elements

=== Changed

* cleaned space management


== [3.2.2] - 2022-04-21

=== Added

* &#35;124: `&#35;[+value(1, {'TEXTUAL':true, agree: getAnonFS() })]` now outputs `une` in French

=== Fixed

* Empty bullet lists no longer write ul start and end tag
* eatSpace symbol can now work without space before or after
* clearer error message when giving a gender instead of an object that should have a gender


== [3.2.1] - 2022-03-15

=== Added

* doc: adding the docker recipe from `reinoldus` to cook templates into a new docker image

=== Fixed

* ` with ` keyword for an assembly in `eachz` no longer matching if it appears as text in the assembly


== [3.2.0] - 2022-01-22

=== Added

* &#35;109: There can now be 2 levels of assembly in `eachz` and `itemz`. See in xref:mixins_ref:eachz_itemz.adoc#combined[2 levels assembly in eachz/itemz doc].

=== Fixed

* &#35;112: in French, "ainsi que à les" now contracts as "ainsi qu'aux"


== [3.1.2] - 2022-01-04

=== Fixed

* `\#` present in documentation are now corrected in `&#35;` (thanks to recipe https://github.com/asciidoctor/asciidoctor/issues/3415)

=== Changed

* doc: indexation will remain every 48 hours and automatic


== [3.1.1] - 2022-01-04

=== Changed

* doc: newer version of Algolia for search
* doc: changelog cut in different parts for better indexation


== [3.1.0] - 2021-12-28

=== Added

* support for `PARTICIPLE_PRESENT` and `PARTICIPLE_PAST` in English tenses (as requested in &#35;84)
* synonyms: `{mode: 'once'}` now avoids to trigger last triggered alternative after a reset (&#35;110)


== [3.0.4] - 2021-12-23

=== Added

* &#35;103: `value` tag now accepts a mixin as first argument

=== Fixed

* dependencies update


== [3.0.3] - 2021-12-04

=== Fixed

* bug &#35;97: fixes spaces in tag name interpolation and attributes (thanks Mathias)


== [3.0.2] - 2021-10-19

=== Fixed

* `curl` example is fixed
* checking asm mode for 'paragraph' before throwing a paragraph error


== [3.0.1] - 2021-07-25

=== Added

* `pug_mixins` documentation

=== Fixed

* tok var definition fix in tag function (thanks Mathias Winckel)
* added the exception 'cama' (Spanish gender)


== [3.0.0] - 2021-05-06

It is a major version because there are breaking changes.

=== Added

* you may use RosaeNLG without using templates, accessing directly the low level JavaScript API; support is experimental. See xref:integration:rosaenlg-no-pug.adoc[Usage without Pug templates]
* there are now some "universal tenses" defined, which work for multiple languages; see xref:mixins_ref:verbs.adoc#universal_tenses[Universal tenses table]


=== Changed

*There are 3 breaking changes that affect existing templates.*

==== `ref` and `refexpr` must be reference to mixins

`ref` and `refexpr` must now be reference to mixins (and no more strings), and they must be referenced after being declared.

.Change on `ref` and `refexpr`
[options="header"]
|===
a|
Before
a|
....
- var PRODUCT = {};
- PRODUCT.ref = 'PRODUCT_ref';
mixin PRODUCT_ref(obj, params)
  | the ring
....
a|
After
a|
....
- var PRODUCT = {};
mixin PRODUCT_ref(obj, params)
  | the ring
- PRODUCT.ref = PRODUCT_ref;
....
|===

Your templates will probably fail at runtime if you don't change them. To migrate:

* search for `.ref` and `.refexpr` in your templates
* put references instead of strings
* move them after the referenced mixin declaration

==== when referencing a mixin, assembly separators properties must not use a string

Assembly separators (`last_separator`, `begin_with_general`, etc.) can either be a string or reference a mixin.
When referencing a mixin, you must now put the mixin as a reference (*no more as a string*), and the mixin must have been defined before.

If you don't migrate, your templates will not fail, but *the text will be wrong*: you will have the mixin name in the output.

To migrate, search for all assemblies (`eachz` and `itemz`) and change their properties if they reference mixins.

==== mixins and objects cannot have the same name

Mixins are now functions, which have a name; you cannot have mixins and objects having the same name, e.g.
....
mixin phone
  | bla bla
- var phone = {};
....
is now invalid.

Your templates will probably fail at runtime if you don't change them. Rename conflicting mixins or objects.


== Older changelogs

xref:changelog_2.x.x.adoc[2.x.x versions]
xref:changelog_1.x.x.adoc[1.x.x versions]
xref:changelog_0.x.x.adoc[0.x.x versions]
