// Copyright 2021 Ludan Stoecklé
// SPDX-License-Identifier: CC-BY-4.0
= Changelog

////
https://keepachangelog.com/en/0.3.0/
== [Unreleased]

=== Added


=== Fixed


=== Changed

////

== [Unreleased]

=== Added


=== Fixed


=== Changed

* doc: newer version of Algolia for search
* doc: changelog cut in different parts for better indexation


== [3.1.0] - 2021-12-28

=== Added

* support for `PARTICIPLE_PRESENT` and `PARTICIPLE_PAST` in English tenses (as requested in \#84)
* synonyms: `{mode: 'once'}` now avoids to trigger last triggered alternative after a reset (\#110)


== [3.0.4] - 2021-12-23

=== Added

* \#103: `value` tag now accepts a mixin as first argument

=== Fixed

* dependencies update


== [3.0.3] - 2021-12-04

=== Fixed

* bug \#97: fixes spaces in tag name interpolation and attributes (thanks Mathias)


== [3.0.2] - 2021-10-19

=== Fixed

* `curl` example is fixed
* checking asm mode for 'paragraph' before throwing a paragraph error


== [3.0.1] - 2021-07-25

=== Added

* `pug_mixins` documentation

=== Fixed

* tok var definition fix in tag function (thanks Mathias Winckel)
* added the exception 'cama' (Spanish gender)


== [3.0.0] - 2021-05-06

It is a major version because there are breaking changes.

=== Added

* you may use RosaeNLG without using templates, accessing directly the low level JavaScript API; support is experimental. See xref:integration:rosaenlg-no-pug.adoc[Usage without Pug templates]
* there are now some "universal tenses" defined, which work for multiple languages; see xref:mixins_ref:verbs.adoc#universal_tenses[Universal tenses table]


=== Changed

*There are 3 breaking changes that affect existing templates.*

==== `ref` and `refexpr` must be reference to mixins

`ref` and `refexpr` must now be reference to mixins (and no more strings), and they must be referenced after being declared.

.Change on `ref` and `refexpr`
[options="header"]
|===
a|
Before
a|
....
- var PRODUCT = {};
- PRODUCT.ref = 'PRODUCT_ref';
mixin PRODUCT_ref(obj, params)
  | the ring
....
a|
After
a|
....
- var PRODUCT = {};
mixin PRODUCT_ref(obj, params)
  | the ring
- PRODUCT.ref = PRODUCT_ref;
....
|===

Your templates will probably fail at runtime if you don't change them. To migrate:

* search for `.ref` and `.refexpr` in your templates
* put references instead of strings
* move them after the referenced mixin declaration

==== when referencing a mixin, assembly separators properties must not use a string

Assembly separators (`last_separator`, `begin_with_general`, etc.) can either be a string or reference a mixin.
When referencing a mixin, you must now put the mixin as a reference (*no more as a string*), and the mixin must have been defined before.

If you don't migrate, your templates will not fail, but *the text will be wrong*: you will have the mixin name in the output.

To migrate, search for all assemblies (`eachz` and `itemz`) and change their properties if they reference mixins.

==== mixins and objects cannot have the same name

Mixins are now functions, which have a name; you cannot have mixins and objects having the same name, e.g.
....
mixin phone
  | bla bla
- var phone = {};
....
is now invalid.

Your templates will probably fail at runtime if you don't change them. Rename conflicting mixins or objects.


== Older changelogs

xref:changelog_2.x.x.adoc[2.x.x versions]
xref:changelog_1.x.x.adoc[1.x.x versions]
xref:changelog_0.x.x.adoc[0.x.x versions]
