== Filter functions

Filtering is used to clean the text after generation, adding caps and removing extra punctuation. See <<filter_mechanism.adoc, Filter mechanism documentation>>.
It is regexp based and will have as an input a string, previously generated by Pug.

The filtering mechanism is called either via the `filter(mixinName, params)` mixin, or automatically via `renderFile`. It can also be explicitely disabled when you use FreeNLG as a plain Pug engine.

=== The automatic mechanim vs the explicit mixin

By default FreeNLG will automatically filter its whole output. You get the final filtered result.

Still you might prefer using the `filter` mixin when there are entire sections of your html document (not containing NLG text) that you don't want to filter.

Filtering must not be performed twice:

* If you don't use the `filter` mixin, the whole text will be filtered one at the end.
* If you use the `filter` mixin, it will desactivate the global filtering at the end.

=== The `filter` mixin

The `filter(mixinName, params)` mixin takes 2 arguments:

* `mixinName` is the mixin to call, where you have your text to be generated
* `params` are the params for your mixin (optional)

This is in fact a classic root of your NLG pug template:
....

div
  - var myProduct = ...;
  +filter('product_mixin', myProduct)

mixin product_mixin(product)
  ...

....

TIP: Just after calling this mixin, the unfiltered string (the original one) is available in `util.lastUnfiltered`. This is useful for debug.


=== Protect sections from being filtered

Filtering is nice because it will automatically manage capitalization etc. for you. But sometimes you want to disable this mechanim for some sections: _Baba Inc. is a nice company_ instead of _Baba Inc. Is a nice company_.

Also, filtering currently does not work well when applied on common html tags, like `<i>`, `<b>` or `<a href=...>`.


Use the `protectString(string)` js function to protect your strings from begin filtered.
....
l #{protectString("protected.string")}
....
will output _protected.string_ (and not _protected. String_).

TIP: `protectString(string)` is just a shortcut to `'ยง' + string + 'ยง'`


Use the `protect` tag to protect structures:
....
  l
    protect
      | protected.string
....
will output the same.


=== Disable filtering

When you want to generate texts, filtering is mandatory. But when you simply want to use FreeNLG's Pug features, without any Natural Language generation features, you need to disable filtering:

....
const freenlgPug = require('freenlg');

freenlgPug.renderFile('plainPugTemplate.pug', {
    language: 'en_US',
    disableFiltering: true
});
....

TIP: `language` parameter is not mandatory if you do not generate texts.
