== Multilingual texts

Sometimes you want to generate texts in multiple languages (let's say English and French).

TIP: you will actually have to define the texts in each output language, there's no black nor white magic here.

You can read `util.language` to see the current language thus you can write these kind of multilingual mixins:
....
mixin multilingual
  case util.language
    when 'en_US'
      | fetch the cow!
    when 'fr_FR'
      | fetchez la vache !
....

ifdef::backend-html5[]
++++
<script>
spawnEditor('en_US', 
`mixin multilingual
  case util.language
    when 'en_US'
      | fetch the cow!
    when 'fr_FR'
      | fetchez la vache !
p #[+multilingual]
`
);
</script>
++++
endif::[]

ifdef::backend-html5[]
++++
<script>
spawnEditor('fr_FR', 
`mixin multilingual
  case util.language
    when 'en_US'
      | fetch the cow!
    when 'fr_FR'
      | fetchez la vache !
p #[+multilingual]
`
);
</script>
++++
endif::[]

It is a good practice for maintenance to keep both languages in the same mixins.
