== Agreement of nouns and adjectives

=== Substantive (or how to agree words)

`substantive(word, agreeWith)` will agree the word (with is just a noun) with `agreeWith`.

For instance:
....
-
  var DIAMONDS = {bla: 'bla'};
  setRefNumber(DIAMONDS, 'P');

p #[+substantive("diamond", DIAMONDS)]
....
This will output _diamonds_.

Works in `en_US`, `fr_FR` and `de_DE`.

ifdef::backend-html5[]
++++
<script>
spawnEditor('en_US', 
`-
  var DIAMONDS = {bla: 'bla'};
  setRefNumber(DIAMONDS, 'P');

p #[+substantive("diamond", DIAMONDS)]
`
);
</script>
++++
endif::[]


anchor:agree_adjectives[Agree adjectives]

=== Agree adjectives `agreeAdj`

Use `agreeAdj(adjective, subject)` to agree an `adjective` with a `subject`.

For instance in `fr_FR`:
....
p #[+agreeAdj('luxueux', getAnonymous('F', 'P'))] / #[+agreeAdj('muni', getAnonymous('F', 'P'))]
....
will output _luxueuses / munies_.

ifdef::backend-html5[]
++++
<script>
spawnEditor('fr_FR', 
`p #[+agreeAdj('luxueux', getAnonFP())] / #[+agreeAdj('muni', getAnonFP())]
`
);
</script>
++++
endif::[]


In German you have to indicate both the case and the determiner:
....
p der #[+agreeAdj('alt', 'Gurke', {case:'GENITIVE', det:'DEFINITE'})] Gurke
....
will output _der alten Gurke_.

TIP: You can also use `value` with the `adj` property. `p #[+value('Gurke', {case:'GENITIVE', det:'DEFINITE', adj:'alt'})]` will also output _der alten Gurke_.

ifdef::backend-html5[]
++++
<script>
spawnEditor('de_DE', 
`p der #[+agreeAdj('alt', 'Gurke', {case:'GENITIVE', det:'DEFINITE'})] Gurke
p #[+value('Gurke', {case:'GENITIVE', det:'DEFINITE', adj:'alt'})]
`
);
</script>
++++
endif::[]
