== Possessives with `recipientPossession` and `thirdPossession`

anchor:thirdPossession[thirdPossession]

=== With `thirdPossession`

Use it when you want to talk of a property of an object. If the object you talk about is a ring, you may want to talk about its weight, its size, etc. - texts like _the weight of the ring_, _its size_, etc.

Use `thirdPossession(owner, owned)`:
....
-
  var BAGUE = {};
  BAGUE.ref = 'bague_ref';
mixin bague_ref(obj, params)
  | #[+value('bague', {represents:BAGUE, det:'DEFINITE'})]

p #[+thirdPossession(BAGUE, 'largeur')] / #[+thirdPossession(BAGUE, 'poids')]
....
will output _la largeur de la bague / son poids_.

ifdef::backend-html5[]
++++
<script>
spawnEditor('fr_FR', 
`-
  var BAGUE = {};
  BAGUE.ref = 'bague_ref';
mixin bague_ref(obj, params)
  | #[+value('bague', {represents:BAGUE, det:'DEFINITE'})]

p #[+thirdPossession(BAGUE, 'largeur')] / #[+thirdPossession(BAGUE, 'poids')]
`
);
</script>
++++
endif::[]


As usual `thirdPossession` takes an optional last parameter that is sent as is to the subject.

In Englis you can add `possForm`: `OF` (default) to generate texts like _the width of the ring_ or `S` for _the ring's width_.

In German you can indicate the case:
....
-
  var PRODUKT = {};
  PRODUKT.ref = 'produkt_ref';
mixin produkt_ref(obj, params)
  | #[+value('Gurke', addToParams({represents: PRODUKT, 'det': 'DEFINITE'}))]

p
  | #[+value(PRODUKT)] :
  | 8 cm ist #[+thirdPossession(PRODUKT, 'Durchmesser', {case:'GENITIVE'})] ,
  | grün ist #[+thirdPossession(PRODUKT, 'Farbe', {case:'GENITIVE'})]

....
will output: _die Gurke: 8 cm ist ihres Durchmessers, grün ist ihrer Farbe_.

`addToParams` is required here so that the case is conveyed through the call stack.

ifdef::backend-html5[]
++++
<script>
spawnEditor('de_DE', 
`
-
  var PRODUKT = {};
  PRODUKT.ref = 'produkt_ref';
mixin produkt_ref(obj, params)
  | #[+value('Gurke', addToParams({represents: PRODUKT, 'det': 'DEFINITE'}))]

p
  | #[+value(PRODUKT)] :
  | 8 cm ist #[+thirdPossession(PRODUKT, 'Durchmesser', {case:'GENITIVE'})] ,
  | grün ist #[+thirdPossession(PRODUKT, 'Farbe', {case:'GENITIVE'})]
`
);
</script>
++++
endif::[]

TIP: You can use `value` with `owner` param instead of `thirdPossession`. `#[+value('largeur', {owner: BAGUE})]` is equivalent to `#[+thirdPossession(BAGUE, 'largeur')]`.

=== With `recipientPossession`

_French and English only (partial support for both)_

`recipientPossession(owned)` will output item as if owned by the reader. `#[+recipientPossession(PRODUCT)]` will output _votre bague_ or _vos boucles d'oreille_.

ifdef::backend-html5[]
++++
<script>
spawnEditor('fr_FR', 
`
-
  var BAGUE = {};
  BAGUE.ref = 'bague_ref';
mixin bague_ref(obj, params)
  | #[+value('bague', {represents:BAGUE, det:'DEFINITE'})]

p #[+recipientPossession(BAGUE)]
`
);
</script>
++++
endif::[]
