anchor:value[Value]

== Value mixin

The `value(obj, params)` mixin is the entry point to insert a value in a text. Its behavior depends of the type of `obj`.

INFO: `value` is the entry point of many FreeNLG features. Don't miss it!

=== Structured object

When it is a *structured object*, you have to define how to transform it into text: see <<referring_expression>>.

=== String

When it is a *string*, it will be output as is. You can protect it from untimely capitalization etc. using `protectString`.

Additional parameters:

* `represents` to assign the gender of the word to the representant (in French).
* `det` to add a determinant (French and English); current determinants are `DEFINITE` and `DEMONSTRATIVE`.
* `case` to indicate the case (German only); current cases are `NOMINATIVE` and `GENITIVE`.
* `adj` to indicate an adjective (German only).
* `owner` to indicate an owner (French and German only). See <<mixins_ref.adoc#thirdPossession>>.

In German, `#[+value('Gurke', {case:'GENITIVE', det:'DEFINITE', adj:'alt'})]` will output _der alten Gurke_.

In French, default position of the adjective is after the noun: _les gâteaux délicieux_, but not always: _les bons gâteaux_. Set `adjPos` to `BEFORE` or `AFTER` to change the position :

* `#[+value('homme', {det:'INDEFINITE',  adj:'vieux', adjPos:'BEFORE'})]` outputs _un vieil homme_
* `#[+value('Hollandais', {det:'INDEFINITE',  adj:'vieux', adjPos:'BEFORE'})]` outputs _un vieux Hollandais_


.All those 4 constructions do exactly the same thing
[cols="2"]
|===
a|
Just plain text, and setting gender directly:
....
\| cette bague
- setRefGender(PRODUIT, 'F');
....

a|
Just plain text, and using the dictionnary to set the gender (French or German):
....
\| cette bague
- setRefGender(PRODUIT, 'bague');
....

a|
Using value with `represents` option (and dictionnary lookup):
....
\| cette #[+value('bague', {represents: PRODUIT})]
....

a|
Using value with `represents` and `det` options (and dictionnary lookup):
....
\| #[+value('bague', {represents: PRODUIT, det: 'DEMONSTRATIVE'})]
....

a|
Using simplified syntax (see below):
....
\| #[+value('<ce bague>', {represents: PRODUIT})]
....
|===

TIP: When some words or expressions are not in the dictionnary, you can indicate explicitely the gender: `#[+value('OnePlus 5T', {represents: PRODUKT2, gender:'N', det: 'DEFINITE'})]` will output _das OnePlus 5T_ in German.


anchor:simplified[Simplified syntax]

=== String with simplified syntax

A simplified syntax can be used to indicate a determinant, an adjective and a gender, with `#[+value('<...>')]`.

WARNING: This feature is only available in French and in German and is still quite experimental.

.Examples
[cols="2", options="header"]
|===
| Classic syntax
| Simplified syntax

| `#[+value('caméra', {det:'DEFINITE', adj:'vieux', adjPos:'BEFORE'})]`
| `#[+value("<la vieille caméra>")]`

| `#[+value('gâteau', {det:'INDEFINITE',  adj:'délicieux', number:'P'})]`
| `#[+value("<des gâteaux délicieux P>")]`

| `#[+value('homme', {det:'INDEFINITE', adj:'beau', adjPos:'BEFORE'})]`
| `#[+value('<une beau hommes>')]`

| `#[+value('bague', {det:'DEMONSTRATIVE', adj:'exquis', adjPos:'BEFORE', represents: PRODUIT})]`
| `#[+value('<cette exquis bague>', {represents: PRODUIT})]`

| `#[+value('Gurke', {case:'GENITIVE', det:'DEFINITE', adj:'alt'})]`
| `#[+value("<der alte Gurke>", {case:'GENITIVE'})]`

| `#[+value('Telefon', {case:'ACCUSATIVE', det:'DEFINITE', adj:'neu'})]`
| `#[+value('<der neu Telefon>', {case:'ACCUSATIVE'})]`
|===


Guidelines:

* Supported determinants are definite articles (_le la les_), indefinite articles (_un une des_), and demonstrative pronouns (_ce cet cette ces_).
* Nothing is deducted from the specific article you choose. `<la arbre>` is the same as `<le arbre>`.
* Adjectives must be in dictionnary.
* Adjective can be before or after the noun (put it a the proper place!), and is optional.
* Determinant is optional.
* If nouns are not in the dictionnary, you must provide a gender (M or F). For instance `#[+value('<la bon schwarzwald F>')]` will output _la bonne schwarzwald_.
* You can add a number at the end (S or P).
* The parser will raise an error at runtime if the expression is not properly parsed.
* You can add further parameters (like `{represents: ...}`).
* The parser can be confused in some cases. For instance, in `<le beau hâbleur>`, _hâbleur_ can be both an adjective and a noun, and _beau_ too - even if in this situation it is quite clear that _beau_ is the adjective and _hâbleur_ the noun.


=== Date

When it is a *date*, the `moment` lib will be used to format it. You should put a parameter to indicate how to format it: `#[+value( new Date('1980-04-14') , 'LL')]` will output _April 14, 1980_ in English.

See http://momentjs.com/docs/#/displaying/[displaying dates with moment.js] for options.

TIP: The date has to be a real standard javascript date, not a string. If you have a string parse it before, using `new Date(string)` or `util.moment`.

=== Number

When it is a *number*, you have various options:

* by default it will format the number accordingly to the locale: `562407` will output _562,407_ in `en_US`, _562 407_ in `fr_FR` (thanks to `format-number-french` lib)
* set `AS_IS` flag to `true` to avoid this (available in any language)
* set `TEXTUAL` flag to `true` to transform the number into text: `#[+value(5500, {'TEXTUAL':true })]` will output _five thousand five hundred_
* set `ORDINAL_NUMBER` flag to true to to transform the number into an ordinal number: `#[+value(21, {'ORDINAL_NUMBER':true })]` will output _21st_
* set `ORDINAL_TEXTUAL` flag to true to to transform the number into an ordinal text: `#[+value(21, {'ORDINAL_TEXTUAL':true })]` will output _twentieth_
* use `FORMAT` to set a format directly used by `numeral`. See http://numeraljs.com/#format[numeral.js formats]. Very practical for currencies, %, etc.

INFO: `numeral` takes into account the locale: `+value(104000, {'FORMAT': '0a$'})` will output _104k€_ (yes, €!) when generating French.

.Number formatting support depending on languages
[options="header"]
|=====================================================================
| Feature  | en_US  | fr_FR | de_DE
| Default: standard number formatting | yes | yes | yes
| `TEXTUAL` | yes | yes (but doesn't work with decimal numbers) | yes (doesn't work with decimal numbers)
| `ORDINAL_NUMBER` | yes | yes | yes
| `ORDINAL_TEXTUAL` | yes | yes (up to 100) | yes (up to 100)
| `FORMAT` | yes | yes | yes
|=====================================================================
