== Verbs

A good NLG system is able to agree things and to make conjugations (that's the basis).
Classic structures are subject/verb or subject/verb/adjective.

Before anything we need to define what subjects can be.

=== Subjects

A subject has to have a gender and a number. A simple way to define a subject is to use an existing js object and to affect him a gender and a number.
....
var PRODUCT = {something: 'somehow'};
setRefGender(PRODUCT, 'M');
setRefNumber(PRODUCT, 'P');
....

TIP: in French or German, `setRefGender(PRODUCT, 'bague');` will look for `bague` in the dictionnary and set `PRODUCT` gender to `F`. Same as `setRefGender(PRODUCT, 'F');` here.

If you don't want to bother with objects because they don't exist or are too insignificant to be really created, you can ask the system to provide anonymous subjects:
....
var subjS = getAnonymous('M', 'S');
....
`getAnonymous(gender, number)` will create an anonymous object and record is with the right gender and number.


At last, you can use complex structure like <<referring_expression>> to define your subjects.

=== Conjugate verbs `subjectVerb` and `verb`

Use `subjectVerb(subject, verb)` to agree a verb with a subject.
`+subjectVerb(PRODUCT, 'shine')` will output _the ring shines_.

`verb(subject, verb)` will just output the agreed verb but not the subject.
`+verb(PRODUCT, 'shine')` will output _shines_.

Instead of putting directly a verb (like `shine`), you can add extra parameters for the verb, typically the tense.
`+subjectVerb(PRODUCT, {verb:'shine', tense:'PAST'})` will output _the ring shined_.

`subjectVerb` and `verb` also accept a last optional param which is transmitted as is to the subject. For instance, `+subjectVerb(PRODUCT, 'shine', {REPRESENTANT: 'refexpr'})` will force the referring expression representation of the product, thus outputting something like _it shines_.

=== English support

English conjugations are made with `compromise` lib. Accepted tenses are:

* `PRESENT` which is also the default value
* `PAST`
* `FUTURE`

=== French support

Any verb of all 3 verb groups are available thanks to `lefff` derived resource: `ils #[+verb(subjMP, 'oindre')]` will output _ils oignent_.

Supported tenses are:

* `PRESENT`
* `FUTUR`
* `IMPARFAIT`
* `PASSE_SIMPLE`
* `CONDITIONNEL_PRESENT`
* `IMPERATIF_PRESENT`
* `SUBJONCTIF_PRESENT`
* `SUBJONCTIF_IMPARFAIT`
* `PASSE_COMPOSE`
* `PLUS_QUE_PARFAIT`

For `PASSE_COMPOSE` and `PLUS_QUE_PARFAIT`, you have to indicate:

. Which auxiliary to use (_être_ or _avoir_): set `aux` to `AVOIR` or `ETRE`
. With what to agree the participle (optional, masculine singular being the default): set `agree`

For instance:

* `elles #[+verb(getAnonFP(), {verb: 'sortir', tense:'PASSE_COMPOSE', aux:'ETRE', agree: getAnonFP()})]` will generate _elles sont sorties_
* `elles #[+verb(getAnonFP(), {verb: 'sortir', tense:'PASSE_COMPOSE', aux:'AVOIR'})] la poubelle` will generate _elles ont sorti la poubelle_


If the auxiliary is not set, these rules will apply:

* pronominal verbs always use `ETRE`
* there is a short list of verbs that always take `ETRE`
* transitive verbs rather take `AVOIR`


TIP: `PASSE_COMPOSE` can be used to mimic the passive form. `elle #[+verb(getAnonFS(), {verb: 'convoquer', tense:'PASSE_COMPOSE', aux:'ETRE', agree:getAnonFS()})]` will output _elle est convoquée_. But `elle #[+subjectVerbAdj(getAnonFS(), 'être', 'convoqué')]` generates the same output and is much simplier.

Pronominal form using `pronominal:true`: `ils #[+verb(getAnonMP(), {verb: 'immerger', tense:'IMPARFAIT', pronominal:true})]` will output _ils s'immergeaient_.

=== Conjugate verbs _and_ agree adjectives with `subjectVerbAdj`

Use `subjectVerbAdj(subject, verbInfo, adjective)` to directly generate a subject, a conjugated verb and an agreed adjective.
`#[+subjectVerbAdj(PRODUCT, 'être', 'luxueux')]` will output _la bague est luxueuse_.

`subjectVerbAdj` also accepts a last optional parameter that is transmitted as is to the subject.

See <<agree_adjectives>>.


=== Language support for verbs

Coverage on verbs is still scarce.

.Language support for verbs
[options="header", cols="3"]
|=====================================================================
| Characteristic  | en_US  | fr_FR
| Irregular verbs | yes (and coverage should be good) | group 1 and 2 only (no group 3 support yet)
| Tenses
a|
* `PRESENT`
* `PAST`
* `FUTURE`
a|
* `PRESENT`
* `INDICATIF_PASSE_COMPOSE`
* (more to come hopefully)
| Persons | 3rd person singular & plural only | 3rd person singular & plural only
|=====================================================================


