= Quick Start

[#nodejs]

== Using node.js

In some js file:
[source,javascript]
....
const rosaenlgPug = require('rosaenlg');

console.log( rosaenlgPug.renderFile('testNLG.pug', {
    language: 'en_US',
    data: ['apples', 'bananas', 'apricots']
}) );
....

In a `testNLG.pug` file:
....
p
  eachz fruit in data with { separator: ',', last_separator: 'and' }
    | #{fruit}
....

This will output `<p>Apples, bananas and apricots</p>`.


== In the browser

You can give it a try right now:
++++
<script>
spawnEditor('en_US', 
`- var data = ['apples', 'bananas', 'apricots', 'pears'];
p
  eachz fruit in data with { separator: ',', last_separator: 'and', begin_with_general: 'I love', end:'!' }
    | #{fruit}
`, 'I love apples, bananas, apricots and pears!'
);
</script>
++++

and read the xref:browser:intro.adoc[browser compilation and rendering] documentation.


anchor:docker[Docker]

== Using Docker

With `fruits.pug` on your local filesystem:
....
- var data = ['apples', 'bananas', 'apricots', 'pears'];
p
  eachz fruit in data with { separator: ',', last_separator: 'and', begin_with_general: 'I love', end:'!' }
    | #{fruit}
....

On your local command line:
[source,bash]
....
cat fruits.pug | docker run -i registry.gitlab.com/rosaenlg-projects/rosaenlg/cli:latest -l en_US
....

You should obtain `<p>I love apples, bananas, apricots and pears!</p>`.

For more advanced usages, read xref:integration:docker-cli.adoc[Docker image for CLI]:

* render files that contain `include` (which is very common)
* watch for templates files changes and render them continuously

Once the templates are developed, you can use xref:integration:node-server.adoc[Docker RosaeNLG server] to render them through an API.


== Other integrations: Java, API, etc.

If you want to use RosaeNLG in a Java application, or call RosaeNLG through an API, or just use Docker, see xref:integration:integration.adoc[the complete integration guide].
