// Copyright 2019 Ludan Stoecklé
// SPDX-License-Identifier: Apache-2.0

// tag::intro[]
== Our goal

This tutorial will guide you through a basic use of RosaeNLG. You will apply RosaeNLG to a basic usecase which is generating texts (Natural Language texts) to describe OnePlus smartphones.

You should read a basic link:https://pugjs.org/[Pug] tutorial as a prerequisite.

Our OnePlus phone data will come from link:https://www.phonearena.com/phones/compare/OnePlus-5T,OnePlus-5,OnePlus-3T/phones/10695,10501,10313[this site].

// end::intro[]

// tag::node_setup[]

== Node environment setup

TIP: This tutorial focuses on server-side rendering using node.js. But you can run your templates client side xref:browser:intro.adoc[in the browser].

TIP: With the integrated editor you will also be able to run directly the tutoriel in your browser.


You can skip this part if you are familiar with node.js environment setup as it's completely standard.

* install `node.js` and `npm` in your environment
* create a `tutorial` folder somewhere
* `npm init` and just accept whatever it says/asks
* `npm install rosaenlg` will download rosaenlg and end up with something like `+ rosaenlg@x.x.x`
* create an `tuto.js` file, just put `console.log("hello NLG");` inside of it
* `node tuto.js` should output `hello NLG` (PS that's not really Natural Language Generation yet)

// end::node_setup[]


// tag::initial_data[]

== Initial data

Our initial data. Put it in your `tuto.js` file.
[source,javascript]
....
include::tuto_fragments.js[tags=data]
....

// end::initial_data[]


// tag::plumbing[]

== Plumbing & first texts

You need the `rosaenlg` lib, thus, add this at the beginning of your `tuto.js` file:
[source,javascript]
....
include::tuto_fragments.js[tags=require]
....

In the same file, call a pug template (we will create the template just after):
[source,javascript]
[subs=attributes+]
....
let res = rosaenlgPug.renderFile('tuto.pug', {
    language: '{rosaenlg_lang}',
    phone: phones[0]
});
console.log( res );
....
This will render the `tuto.pug` template. Parameters:

* choosing a language (here `language: '{rosaenlg_lang}'`) is mandatory. 
* `cache: true` tells Pug that it does not need to recompile the template at each call (in practice it is faster).
* for the other properties you can organize them as you want; here we just put a `phone` property with our first phone.

Create a `tuto.pug` file with this content:
....
p #{phone.name}
....
This first template is just standard Pug syntax: we output the name of the phone.

When you render the template (using `node tuto.js`) you should get: +
_<p>OnePlus 5T</p>_

_(ok, it's not really NLG yet)_

// end::plumbing[]


// tag::looping[]
Let's generate some text for each phone. In your `tuto.js` file:
[source,javascript]
[subs=attributes+]
....
include::tuto_fragments.js[tags=mainLoop]
....

In `tuto.pug`:
....
- let phone;
each phoneElt in phones
  - phone = phoneElt;
  p #{phone.name} . #[+colors]
....

WARNING: Here we have put the main loop directly in the Pug template. In real cases, it is better to loop outside (directly in the JavaScript caller), as this allows an easy reset of RosaeNLG and Pug between each rendering, which is much better for performance.

// end::looping[]

// tag::display_elts[]
* `value` is a mixin that will output the value respecting the locale.
* `itemz > item` is much like `synz > syn`, except that it will not choose one alternative, but list all the items.
* The js object after `itemz` tells RosaeNLG how to assemble elements. It is mandatory. `separator` and `last_separator` work exactly the same way as in the `eachz` structure.

Do not forget to call this mixin:
....
mixin phone
  | #[+intro] .
  | #[+colors] .
  | #[+display] .
....
// end::display_elts[]

// tag::begin_with_general_why[]
`begin_with_general` tells RosaeNLG what the texts should begin with. You could have put it outside the mixin (just before), but it's a good practice to put them inside: for instance, when the list of the elements is empty, RosaeNLG will not output the `begin_with_general` content.
// end::begin_with_general_why[]

// tag::refexpr_concept[]
This is called _referring expressions_ in NLG. The first time we talk about something we use its _representant_ representation and after we use the _referring expression_ representation. We want RosaeNLG to care for that automatically.
// end::refexpr_concept[]

// tag::has_said_solution[]
The pattern hasSaid/recordSaid pattern, here used twice, is the following: _if we haven't talked about something:_

. _We talk about it_
. _We record that we talked about it_

TIP: You must use these built-in mechanisms and not rely on your own variables or hashmaps that you would set along text generation, as RosaeNLG goes back and forth in the text rendering.

TIP: You also need a `deleteSaid('BATTERY')` in the main loop, as we must talk of the battery for each phone.

// end::has_said_solution[]

// tag::empty_synonym[]
TIP: When an empty synonym is triggered (which can happen here), RosaeNLG will just choose another one.
// end::empty_synonym[]




// tag::congrats[]
== Congratulations!

*Sincere Congratulations!* 🎆
// end::congrats[]
