name: simple workflow
'on':
  push:
    branches:
      - '*'
      - '!v*.*.*'
jobs:
  build_test:
    name: 'Build, test and save build artifacts'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: some debug
        run: |
          # git branch -a
          BRANCH="$(git branch --show-current | sed 's/\n//')"
          echo "branch: --${BRANCH}--"

          BRANCH2="$(git branch --show-current)"
          echo "branch2: --${BRANCH2}--"
      - name: inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x
      - name: use proper version of node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: cache node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: '${{ runner.OS }}-node-${{ hashFiles(''**/yarn.lock'') }}'
          restore-keys: |
            ${{ runner.OS }}-node-
      - name: cache performance monitoring
        uses: actions/cache@v3
        with:
          path: packages/perf-monitoring/benchmark-*.json
          key: benchmark
      - name: check environment versions
        run: |
          npm -v
          node --version
      - name: install environment
        run: |
          npm install -g pegjs
          npm install -g lerna
          yarn install
          rm -f packages/rosaenlg/dist/rollup/*.js
      - name: build
        run: |
          lerna run build
      - name: test
        run: |
          lerna run test
          # checking performance monitoring packages
          ls -l packages/perf-monitoring/benchmark-*.json
      - name: Zip artifact for deployment
        run: |
          # zip info
          zip --version
          # log where we are
          echo starting zip process
          pwd
          ls -l
          # zip
          zip --recurse-paths --quiet build.zip packages/*/dist packages/*/resources_pub packages/*/dist packages/*/coverage packages/*/lib packages/rosaenlg-lambda/.serverless packages/rosaenlg-antora-ui/build packages/rosaenlg-doc-website/main packages/rosaenlg-doc-website/gh-pages
          # check result
          ls -l build.zip
      - name: upload build
        uses: actions/upload-artifact@v3
        with:
          name: 'build-${{ env.GITHUB_REF_SLUG }}'
          path: build.zip
          retention-days: 1
  sonarcloud:
    name: SonarCloud
    needs:
      - build_test
    runs-on: ubuntu-latest
    steps:
      - name: inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x
      - uses: actions/checkout@v3
      - name: download build
        uses: actions/download-artifact@v3
        with:
          name: 'build-${{ env.GITHUB_REF_SLUG }}'
      - name: unzip build
        run: |
          echo starting unzip of the build
          # log where we are
          pwd
          ls -l
          # unzip
          unzip build.zip
          # check result
          ls -l
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
