name: just docker server - patch only!

on: 
  workflow_dispatch:
    inputs:
      ROSAENLG_VERSION:
        description: RosaeNLG version
        required: true

jobs:
  docker_server:
    name: Docker Server
    runs-on: ubuntu-latest
    steps:
      - name: inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
      - uses: actions/checkout@v2
      - name: download build
        uses: actions/download-artifact@v2
        with:
          name: 'build-${{ env.GITHUB_REF_SLUG }}'
          path: ./packages
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Build test image
        uses: docker/build-push-action@v2.0.1
        with:
          context: packages/rosaenlg-node-server/docker/
          file: packages/rosaenlg-node-server/docker/Dockerfile
          load: true
          tags: '${{ env.DOCKER_TEST_TAG }}'
          build-args: |
            ROSAENLG_VERSION=${{ github.event.inputs.ROSAENLG_VERSION }}
        env:
          DOCKER_TEST_TAG: 'rosaenlg/server:test_${{ env.GITHUB_REF_SLUG }}'
      - name: Test image
        run: |
          echo "checking curl..."
          curl --version
          cd packages/rosaenlg-node-server/docker/
          echo "starting docker container..."
          docker run -d -p 5000:5000 $DOCKER_TEST_TAG
          echo "sleeping..."
          sleep 20
          echo "list processes"
          ps -ef
          chmod +x ./test.sh
          echo "run test"
          /bin/sh ./test.sh
        env:
          DOCKER_TEST_TAG: 'rosaenlg/server:test_${{ env.GITHUB_REF_SLUG }}'
      - name: Build and push final image
        uses: docker/build-push-action@v2.0.1
        with:
          context: packages/rosaenlg-node-server/docker/
          file: packages/rosaenlg-node-server/docker/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_FINAL_TAG }}
            rosaenlg/server:latest
          build-args: |
            ROSAENLG_VERSION=${{ github.event.inputs.ROSAENLG_VERSION }}
        env:
          DOCKER_FINAL_TAG: 'rosaenlg/server:${{ github.event.inputs.ROSAENLG_VERSION }}'
